### ISSUE TITLE
dnd problem when parent along with children moves under another node

### ISSUE THREAD

**Issue by tharasp** [deitch/jstree-grid#101]
When a parent along with its children is moved under another node, the link between `jstree` and grid seems to be lost. The highlighting shows some problem in tree and grid data correspondence. 

Fiddle: http://jsfiddle.net/gw9ch970/124/

![pic](https://cloud.githubusercontent.com/assets/10546159/8153782/4877bff4-1350-11e5-8e81-86218c4f344c.png)

**Comment by deitch** [comment]
Can you be more specific on the behaviour? 

1. what exactly do you do to cause the behaviour?
2. what do you expect to happen?
3. what actually happens?

Not as interested in the underlying cause ("link seems to be lost") as the actual reproducilbe behaviour.

**Comment by tharasp** [comment]
Fiddle: http://jsfiddle.net/gw9ch970/137/

When I drag a non-leaf node (P1.1.2) and drop it under node (P1.2), the node along with its children drops in successfully. But the unit data in grid for the moved in nodes seems messed up (in what order, I don't understand). The row highlighting shown is broken. 

But no problem seems to occur when I drag and drop a leaf node. 
Hope this is understandable.

**Comment by deitch** [comment]
OK, yes, that makes it very clear. Will look at it next day or two.

**Comment by deitch** [comment]
Something really strange about how it is rebuilding the nodes.

**Comment by deitch** [comment]
3.2.3 fixes this. It causes it to relocate all children when a parent moves.

This is the challenge of doing it in table. On the other hand, alignment when it was in the `li` elements was a nightmare...

Pushing out now.
