### ISSUE TITLE
Another issue from search and show_only_matches

### ISSUE THREAD

**Issue by hieuhx01001** [deitch/jstree-grid#103]
Hi deitch ! 
I found another issue from search and show_only_matches (it is related with issue https://github.com/deitch/jstree-grid/issues/88). I used your jsfiddle : http://jsfiddle.net/soujyx6n/
 - Search with any value 1, 2, 3 (mine is 1)
 - Click to collapse and click again to expand root (child1)

The problem is when you collapse and expand root. it show all grid of child of this root, but only show name that matching with search. In my case that show 3 grid and have one with no name.

**Comment by deitch** [comment]
So the issue is that when you expand and collapse, it adds the rows below that should still be hidden?

**Comment by hieuhx01001** [comment]
yes,I think it should be hidden, no need to show all grid when search with only match option

**Comment by deitch** [comment]
Oh my, I let this slip. Oops. Accidentally archived the email reminder.

**Comment by deitch** [comment]
This has been quite the challenge. Prior to version 3.1.0, the grid was just divs and spans added to the `<li>` of the tree. All of the expansion worked beautifully, but controlling events and aligning was a nightmare, so 3.1.0 was the big switch to a table. But now the table requires lots of complex logic to manage showing/hiding and sorting the grid cells. 

This problem ran afoul of that.

OK, so where is it doing the expansion? Digging..

**Comment by deitch** [comment]
Even stranger, if you look at the sample file treegrid.html, it has a search, and the issue does not recur there.

**Comment by deitch** [comment]
@hieuhx01001 I cannot figure out what your search functions are doing. Why the complex search? Why not just use the built-in jstree search function? See updated fiddle. http://jsfiddle.net/soujyx6n/1/

**Comment by side-by-side** [comment]
I'm using native jstree.search('blah') and the bug is here. When close and reopen a node, grids for all its children become visible when should be hidden except matched rows.
All exactly as described in the issue.

**Comment by deitch** [comment]
Still not sure I get this. So you search for a value, then collapse and expand, and then what happens?

**Comment by side-by-side** [comment]
I can't show this right now in jsFiddle or screenshots, because i already "reimplemented" search functionality via ajax calls (by `jstree.refresh()`) and not using native `jstree.search()` anymore.

Look at jsFiddle that is in start post: http://jsfiddle.net/soujyx6n/.
1. Search for "1".
2. The result is Root → Child1 → Child 1-1
3. Close Child1.
4. Open Child1. We have the same highlighted search result, but one extra grid row, for Child2-2, that was hidden before close/open and should be hidden now.

**Comment by deitch** [comment]
Updated your fiddle. The latest jstree-grid respects the column widths much more tightly... which made the previous one unreadable.

**Comment by deitch** [comment]
Ah, now I see it!

**Comment by side-by-side** [comment]
Ok, cool, now you see it :)
Seems like jsTreeGrid not taking into account "show_only_matches" option on node open.

**Comment by deitch** [comment]
Had to fix a bunch of other search related issues. Strangely, now when I run it, the tree itself doesn't seem to respect the `show_only_matches` option. Look at the latest release via the test file? https://github.com/deitch/jstree-grid/blob/master/tests/widths-test.html

**Comment by srkunze** [comment]
Before I start complaining: great plugin! Thanks. :)

Unfortunately, I can confirm the bug. I used the latest version in the repository.

**Comment by deitch** [comment]
> Before I start complaining: great plugin! Thanks. :)

Thank you. I wish it weren't quite as much effort to support. :-)

> Unfortunately, I can confirm the bug. I used the latest version in the repository.

Yeah, I can as well. Try and squeeze this in between now and LinuxCon/ContainerCon next week (I'm presenting on networking containers).

I just updated the fiddle by changing the "Open" and "Close" columns to have different data. This makes it pretty clear that when you do step 4 above "Open child", it is rendering the grid cells for "Child 2-2" and *not* doubling "Child 1-1".

This probably means that opening a branch node is not respecting `show_only_matches`.

**Comment by deitch** [comment]
@vakata can you help here? No need to read the whole thread. Here is he problem

1. When I search, if `show_only_matches` is enabled, it only shows those matching. This is fine.
2. If search is still in effect, and I close and open a node, the `open_node` still only shows those nodes that match.

Where in `open_node` does it check to see if search is enabled and decide to show or not show the node? I found `open_node` here https://github.com/vakata/jstree/blob/master/src/jstree.js#L2522 but couldn't figure out how it decides, "search is enabled, let me check before showing it."

**Comment by deitch** [comment]
Never mind @vakata I figured it out.

**Comment by deitch** [comment]
Fixed and published v3.5.18.
