### ISSUE TITLE
jstree-hovered is missing in columns in last version

### ISSUE THREAD

**Issue by jiemon** [deitch/jstree-grid#106]
If I'm right You fixed this in #46 
But now all rows is highlighted only when I hover over first column (with LI ). I use jstree 3.1.1 and last version of jstreegrid

**Comment by deitch** [comment]
How did I miss this? I just realized it was there now. Oops, sorry.

I don't understand the problem. Is hovered working or not? Can you throw up a jsfiddle describing the problem?

**Comment by dallincoons** [comment]
+1

**Comment by deitch** [comment]
@dallincoons is this an issue? I just ran the sample file (again). A row is highlighted whether I hover the pointer over the first column, last column or any in between.

**Comment by dallincoons** [comment]
Here's a jsfiddle http://jsfiddle.net/joergwork/h3368/


When you hover over the price column, nothing is highlighted

jstree-grid #59 - JSFiddle<http://jsfiddle.net/joergwork/h3368/>
jsfiddle.net
Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.




________________________________

**Comment by deitch** [comment]
Looks like you are using an old version of jstreegrid. Did you try with the latest? Same as yours, just updated jstreegrid.js

http://jsfiddle.net/pto4hcdm/
