### ISSUE TITLE
jstreegrid version issue  with jstree 

### ISSUE THREAD

**Issue by arunsharmadev** [deitch/jstree-grid#107]
I am using Jstree ( v3.2.0)  with jstreegrid ( \* $Revision:  3.1.0-beta2 $ ) , This is working fine but when I upgrade to latest jstreegrid version 3.2.1 , the grid columns are not showing .  I checked if the files are getting downloaded and I could see it in the resource file . I am not sure why the grid columns dont show up with the new version . The following works but when I use the second line ( uncomment with first one commented ) it does not work 

```
<apex:includeScript value="{!URLFOR($Resource.JSTREEGRID , '/' )}"/>    

<!--  <apex:includeScript value="{!URLFOR($Resource.jstreegrid_new , '/' )}"/>  --> 
```

To be safe , I am just loading the jstreegrid.js as a stand alone file in both cases so that there is SFDC code issue here . 

The reason I am looking for the new version is that the current treegrid columns because disoriented & misaligned if the length of the value exceed the size of the column and it goes into two rows . I have successfully loaded large tree but having issue with the column widths . 

Here is the loadtree function

``` javascript
function loadtree(myjson)
   {     
        $(document).ready(function () {

            $('#jstree').jstree({
                "plugins": [ "contextmenu",  "massload", "search", "sort","state", "types", "wholerow", "grid"],

                        check_callback : true,


                    "search": {

                    "case_insensitive": false,
                        "show_only_matches": false


                },


                    "types": {


                    "root" : {
                      "icon" : "/static/3.2.0/assets/images/tree_icon.png",
                      "valid_children" : ["default"]
                    },
                    "default" : {
                      "valid_children" : ["default","file"]
                    },
                    "file" : {
                      "icon" : "glyphicon glyphicon-file",
                      "valid_children" : []
                    }



                         },


                "contextmenu": {
                "items": function (node) {
                    return {
                        "view": {
                            label: "View Record",
                            action: function (obj) {
                                window.open("/" + node.id);
                            }
                            ,
                          "quote" : {
                              label: "Quote", 
                              action: function(obj) { 
                                  $j("#jstree").jstree(true).edit(node)
                              }
                          }

                        }

                    }


                }
            },




                    'grid': {
                    'columns': [{
                        'width': 300,
                            'header': 'Summary' ,
                            'tree' : true ,
                              'resizable' : true ,
                              title: "_DATA_"
                    }

                    ,
                     {
                        'width': 125,
                            'header': 'Primary M',
                            'value': function (node) {
                            return (node.primarymls);
                        }
                    }

                       , {
                        'width': 100,
                            'header': 'Type',
                            'value': function (node) {
                            return (node.reltype);
                        }
                    }

                    ,
                     {
                        'width': 100,
                            'header': 'Phone' ,

                            'value': function (node) {
                            return (node.phone);
                        }
                    }

                    ,

                    {
                        'width': 75,
                            'header': '$T',
                            'value': function (node) {
                            return (node.t);
                        }
                    }, {
                        'width': 90,
                            'header': '$A',
                             'title': 'tas' ,
                            'value': function (node) {
                            return (node.tas);
                        }
                    }, {
                        'width': 50,
                            'header': 'HL',
                            'value': function (node) {
                            return (node.thv);
                        }
                    }, {
                        'width': 50,
                            'header': '#O',
                            'value': function (node) {
                            return (node.noofo);
                        }
                    }, {
                        'width': 50,
                            'header': '#A ',
                            'value': function (node) {
                            return (node.noofa);
                        }
                    }, {
                        'width': 50,
                            'header': 'CLC ',

                                 'title': 'totalx' ,
                            'value': function (node) {
                            return (node.totalx);
                        }
                    },
                     {
                        'width': 0,
                            'header': '-',
                            'value': function (node) {
                            return (node.primaryc);
                        }
                    }


                    ]
                },

'massload' : {

        data : myjson
    },


                    'core': {
        "multiple" : false ,

        themes: {"stripes": true ,"theme" : "apple",
      "dots" : true,"icons":true ,

         "variant" : "large"
        },
                  "check_callback" : true,
                  "animation" : 0,


                         data : myjson

                }


            });





        });



$(".search-input").keyup(function() {

        var searchString = $(this).val();
      //  console.log(searchString);
        $('#jstree').jstree('search', searchString);
    });


}
```
1. I am loading the json string first using tkrest api (as per other forum) and then filling up when the load is complete . I am also partially  loading the tree after 2000 + records and then reload the tree (using a link) when it gets completed . The reload works fine but If the no of records are more than 50000 then I have issue with memory . Can I use massload using a function with the same json I have build . I tried but was not sure of the syntax /.Also , will it help the memory issue . The Tree on left , with grid on right (5-6 columns) gets heavy .
2. Searching - I change the case sensitive to true , showmacthing :false as otherwise it is very slow . How can I speedup the search . I did see timeout code which I am trying .

Is there some kind of pagination possible , I can split my json array in a batch of 1000 and load them (next , prev) , is there some example of this 

Arun

**Comment by deitch** [comment]
I am completely lost. First, what is the `tkrest` API? Second, I don't understand how the issue is manifesting itself. 

Put up a jsfiddle reproducing the issue, describe how to do it, and we can try to address it.

In a general sense, jstreegrid relies on jstree events, so it should work with whatever loading method you use. That doesn't mean it isn't getting tripped up somewhere, so with a reproducible problem we can work with it.

**Comment by arunsharmamove** [comment]
Could you please help me with this :- I dont see the grid columns in this versions . 

http://jsfiddle.net/arunsharma74/chvx35t3/

**Comment by deitch** [comment]
That is a very strange fiddle. All of your external resources (jstree, jstreegrid, etc.) are all from localhost:8080. You need to pull them from the Internet.

**Comment by deitch** [comment]
(just saw that you answered today, sorry)

**Comment by arunsharmamove** [comment]
Sorry , I am still using the old version of the Tree Grid . I will revise the fiddle code with the correct include scripts (without localhost)

Arun

**Comment by deitch** [comment]
OK, then we will try to figure it out.

**Comment by arunsharmamove** [comment]
Is it possible for me to demo it ? I can show the demo & also the issues I see .

Arun

**Comment by deitch** [comment]
Demo it? What does that mean? Do you mean to show it live via screenshare? Even if I could find time to do so, it wouldn't help. Need to see active code to be able to help. Why not just load up a fiddle or plunkr?

**Comment by arunsharmamove** [comment]
Ok , but there will too much to reproduce , Its in salesforce .

Arun

**Comment by deitch** [comment]
Oh. That makes it interesting, but still limiting.

Let's say we demo it, and I see it. If I cannot reproduce it on my own, without salesforce, how can I create a fix and test it? The issue itself doesn't come from salesforce per se, but some combination of interactions tripping a bug up in the lib. We need to isolate that set of interactions.

**Comment by arunsharmamove** [comment]
I am facing issues where the jstreegrid columns gets disoriented when I go from one node to other . For large tree with 30k + records . The only way a resolution happens is that I close the node and open it again . Also , the Node & the grid columns alignment go for a toss . I may show this in the fiddle scenario as data may be missing …

**Comment by arunsharmamove** [comment]
Avi,

I do have an issue with the alignment , In this picture David Carter is an agent but shows as an Office when Allen Tate parent node is expanded . It seems the Office record is not refreshed and stays there with the data .

Arun

[cid:image001.png@01D122CE.7E2D9960]

**Comment by deitch** [comment]
No picture attached here.
