### ISSUE TITLE
jstree-grid causes flicker during refresh

### ISSUE THREAD

**Issue by chrisexv6** [deitch/jstree-grid#108]
Adding the jstree-grid plugin to an existing jstree based project.  If I enable the plugin (even without any data provided), everytime I call tree.refresh(true), the whole tree flickers during the refresh.

Not sure if its breaking the "skip loading text" parameter of the refresh call or if something else is going on, but once the jstree-grid plugin is removed the tree goes back to refreshing smoothly.

Using jstree-grid v3.2.3 and jstree v3.2.0

Thanks.

-Chris

**Comment by deitch** [comment]
Right you are. It appears not to be passing the parameters correctly.

I put in a small patch. Try using this gist for jstreegrid.js and see if it works.

https://gist.githubusercontent.com/deitch/a941f551b3d2582b691d/raw/60471b28dbd3b21f8c7ae7140ef4947d56fcc779/jstreegrid-patch.js

**Comment by deitch** [comment]
@chrisexv6 this has been open without comment for 8 months. I am closing it out. If it still is an issue with the latest version, please comment here with a fiddle or plunkr to replicate, and will reopen.
