### ISSUE TITLE
Grid acts weirdly when dragging and dropping

### ISSUE THREAD

**Issue by csm725** [deitch/jstree-grid#110]
Hi,

I am using jstreegrid with great success. However I came across an issue, when rearranging rows using the dnd plugin. 

Sometimes the grid just, for lack of a defined behavior, acts weird - rows are misaligned or overridden with incorrect values, sometimes they are even duplicated. Here is a screenshot, note the data not matching the rows - www.streamable.com/v7gv

Todah rabah!

**Comment by deitch** [comment]
Uh, OK, but this is closed? Did you resolve it?

This is something I have struggled with for a long time. From versions 0.x through <3.0.0, jstreegrid embedded the additional cells by extending each row of the jstree. It made dnd and other create/delete/move rows really easy... but the alignment between columns was an impossible nightmare.

So beginning in 3.0.0, it was changed to table based, which made columns and resizing far superior. But over time, other issues - like dnd - have cropped up.

In truth, the two need to be merged, but that requires essentially either merging it into the core of jstree, or replacing the tree component, neither of which anyone has desire or time to do.
