### ISSUE TITLE
duplicated rows

### ISSUE THREAD

**Issue by vagamond** [deitch/jstree-grid#111]
We developed a web page that uses 7 instances of the jstree with treegrid plugin.
We found a issue that causes SOMETIMES the rows to be duplicated, probably depending on race conditions, because it appears frequently in we act on the tree while another tree is downloading json data.
We tried to deactivate the worker, but no luck.
Surprisingly, the duplication appears only on the added columns, never on the main tree (see attached picture)

Tested just on IE9
![bug](https://cloud.githubusercontent.com/assets/14992863/10303596/1d9ec82c-6c15-11e5-8661-e9a0fc613bcc.png)

jsTree 3.1.0
Treegrid
 * $Date: 2015-06-016 $
 * $Revision:  3.2.3 $
(also tested on previous release)

Any suggestions to debug this issue is welcome!
Best Regards

**Comment by deitch** [comment]
Sorry about the delay here; was busy with client work. 

Can you replicate it in a jsfiddle or plunkr? I know you said it only happens "SOMETIMES", but we still should have some sense of the scenario under which it is happening and an attempt to recreate.

I have seen this kind of thing before, a number of fixed have been pushed out.  

Tell you what. Try with 3.2.7 (latest), and try and get it to replicate in a jsfiddle. Until there is something we can replicate, we are very limited with what we can do.

**Comment by deitch** [comment]
@vagamond you didn't respond. I am assuming that means it no longer is an issue. If it still is, comment here with a fiddle or plunkr and I will reopen.

**Comment by vagamond** [comment]
We developed an alternative solution,

thank you


2016-05-12 9:06 GMT+02:00 Avi Deitcher <notifications@github.com>:
