### ISSUE TITLE
How to provide jstree-grid data in HTML.

### ISSUE THREAD

**Issue by castylx** [deitch/jstree-grid#113]
Hey Guys,

   I'd rather not pass data to the javascript directly.  Is there a way to make this work using HTML and have jstree-grid convert it properly?  I didn't quite understand the <div><span>column</span></div> instructions.  For example, this doesn't work 

````html
      <div id="register-tree" style:"margin-top:0px;">
        <ul>
          <li><a>Project Name Here</a>
            <ul>
              <li><a>SATA</a>
                <ul>
                  <li><a>Reg A</a><div><span>$10</span></div></li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </div>
````
Thanks in advance!

**Comment by deitch** [comment]
Are you trying to use the html input format for jstree, and have it convert the items in the `<li>` into grid nodes?

**Comment by castylx** [comment]
Yes exactly

**Comment by deitch** [comment]
Where would you split the data between what goes in the tree node itself and what is in the grid? The docs for html data in jstree are here https://www.jstree.com/docs/html/

To the best of my understanding, everything between the `<li>` and `</li>` is treated as the node itself, with `a`, `ins` and `ul` child elements remove for later parsing (child nodes, etc.).

This requires two things:

1. A clear spec on "these elements within the `li` will be treated as grid nodes and added. This is fairly straightforward.
2. A way of *removing* those elements from the existing tree, which is much messier. 

The second is the serious issue. With pure data and config, we just use data that is not part of the tree node itself, and jstree therefore ignores. In this case, we would need to actively modify each node of the tree after jstree rendered it. 

I am not sure I want us to go down that path.

**Comment by castylx** [comment]
That for the prompt response Avi, no worries, sounds more trouble than it's worth.  I'll go with the javascript route.

Thanks again!

**Comment by deitch** [comment]
On the other hand, if you could get @vakata to make jstree so that it formally says, "this HTML in each row will not be included," then it would be easier.
