### ISSUE TITLE
Few improvements: line height, "auto" width, hover.

### ISSUE THREAD

**Issue by side-by-side** [deitch/jstree-grid#116]
Dear Avi, i have a few more improvements/fixes to the code. Check them out and decide, which of them should be in the base code.

**1. line-height of the grid rows.**
Now the line-height of the grid rows taken from the “line-height” css style from the first node.
If the contents of a node is multiline, its “line-height” doesn't represent real height anymore.
I suggest this replacement to rely on the node actual “height” instead of “line-height”.
https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L228
This code:
```javascript
var lh = this.element.find("li a:first").css("line-height");
$('<style type="text/css">td.jstree-grid-cell {line-height: '+lh+'}</style>').appendTo("head");
```
Can be replaced with:
```javascript
var anchorHeight = this.element.find("li a:first").outerHeight();
$('<style type="text/css">td.jstree-grid-cell {line-height: '+anchorHeight+'px}</style>').appendTo("head");
```

**2. Allowing use “auto” as default column width.**
For my personal use i had implement this. Maybe it will be useful for others.
I don't now why the default width value is limited only to pixels, maybe there is some problems i haven't saw yet, but i'm using this successfully.
To have an ability to use “auto” as default width i edited these lines:
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L358.
The code:
```javascript
width -= borPadWidth;
```
replaced with:
```javascript
if (width != 'auto') {
	width -= borPadWidth;
}
```
* https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L679.
The code:
```javascript
width = tmpWidth || (width - paddingleft);
```
replaced with:
```javascript
if (width != 'auto') {
	width = tmpWidth || (width - paddingleft);
}
```

**3. Hover whole row when mouse moves inside any grid column.**
For now the row hovered only when mouse enters the column with the jsTree (first usually) and not hovered when mouse enters some of the other columns.
The hover handler fixes this. You should add that handler somewhere in this function: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L762
```javascript
var hoverInHandler = function (node, jsTreeInstance) {
    return function() { jsTreeInstance.hover_node(node); }
};
var hoverOutHandler = function (node, jsTreeInstance) {
    return function() { jsTreeInstance.dehover_node(node); }
};
last.hover(hoverInHandler(t, this), hoverOutHandler(t, this));
```
In addition you could add mouse “pointer” while hovering grid columns.

**Comment by deitch** [comment]
Nice bunch of them. They all seem to make sense at first blush. Why not make them 3 separate pull requests, I can review and pull them right in?

**Comment by side-by-side** [comment]
I'm on it. Wait for a while.

**Comment by deitch** [comment]
Closed in favour of the following PRs:

https://github.com/deitch/jstree-grid/pull/118
https://github.com/deitch/jstree-grid/pull/119
https://github.com/deitch/jstree-grid/pull/120
