### ISSUE TITLE
Missed Ctrl key functionality

### ISSUE THREAD

**Issue by pavlo-tk** [deitch/jstree-grid#117]
In jsTree 3.2.1 (dont know about previous verions) we can use Ctrl key to, for example, select more than one nodes, deselect selected and other stuff (moving, copying).
The most important, i think, that is ability to selecting/deselecting nodes usins Ctrl key, clicking somewhere at the grid columns (not on the actual jsTree, first column usual).
Now in jstree-grid only simple click for selecting is supported.

**Comment by deitch** [comment]
@side-by-side so you are saying the following:

* If I click a node - in the tree column or anywhere in the grid - it selects that row and deselects others.
* If I ctrl-click a node in the tree column, it adds that to the selection (or removes it if already clicked), but not in the grid?

**Comment by deitch** [comment]
@vakata, could use your help here. 

The way this works is simple:

1. Capture a `click` event in any grid node (other than the tree itself, which handles it fine)
2. Trigger a `click.jstree` event, which causes the cell to be selected, etc. It passes on the event itself, so all of the `shiftKey` and `ctrlKey` etc. should be passed through just fine.

But it's not.

Code here:

````JavaScript
node = tree.find("#"+node.attr("id"));
node.children(".jstree-anchor").trigger("click.jstree",e);
````

The event itself that is passed through is a different kind of event. Here is the event `e` captured by the original click and passed on to `.trigger()` in the above code snippet:

````json
altKey: false
bubbles: true
button: 0
buttons: undefined
cancelable: true
clientX: 808
clientY: 66
ctrlKey: false
currentTarget: div#jsgrid_j1_2_col1.jsgrid_j1_2_col.jstree-grid-cell.jstree-grid-cell-regular.jstree-grid-col-1.jstree-grid-cell-last {jQuery210079930421616882090.3613452061545104: 8, align: "", title: "", lang: "", translate: true, …}
data: null
delegateTarget: div#jsgrid_j1_2_col1.jsgrid_j1_2_col.jstree-grid-cell.jstree-grid-cell-regular.jstree-grid-col-1.jstree-grid-cell-last {jQuery210079930421616882090.3613452061545104: 8, align: "", title: "", lang: "", translate: true, …}
eventPhase: 2
handleObj: {type: "click", origType: "click", data: null, handler: function, guid: 50, …}
isDefaultPrevented: function()
jQuery21007993042161688209: true
metaKey: false
offsetX: 69
offsetY: 15
originalEvent: MouseEvent {clipboardData: undefined, screenX: 839, screenY: 177, clientX: 808, clientY: 66, …}
pageX: 808
pageY: 66
relatedTarget: null
screenX: 839
screenY: 177
shiftKey: true
target: div#jsgrid_j1_2_col1.jsgrid_j1_2_col.jstree-grid-cell.jstree-grid-cell-regular.jstree-grid-col-1.jstree-grid-cell-last {jQuery210079930421616882090.3613452061545104: 8, align: "", title: "", lang: "", translate: true, …}
timeStamp: 1447634834630
toElement: div#jsgrid_j1_2_col1.jsgrid_j1_2_col.jstree-grid-cell.jstree-grid-cell-regular.jstree-grid-col-1.jstree-grid-cell-last {jQuery210079930421616882090.3613452061545104: 8, align: "", title: "", lang: "", translate: true, …}
type: "click"
view: Window {undefined: undefined, window: Window, NaN: NaN, document: #document, Infinity: Infinity, …}
which: 1
````

And here is what I see in jstree.js:

````json
currentTarget: a#j1_2_anchor.jstree-anchor.jstree-grid-col-0 {jQuery210079930421616882090.3613452061545104: 21, charset: "", coords: "", href: "./treegrid2.html#", hreflang: "", …}
data: undefined
delegateTarget: div#tree.jstree.jstree-1.jstree-default {jQuery210079930421616882090.3613452061545104: 4, jQuery210079930421616882090.6410034317523241: 5, sizzle-1447634733930: {parentNode: [72, 15, true]}, align: "", title: "", …}
handleObj: {type: "click", origType: "click", data: undefined, handler: function, guid: 17, …}
isTrigger: 3
jQuery21007993042161688209: true
namespace: "jstree"
namespace_re: /(^|\.)jstree(\.|$)/
result: undefined
target: a#j1_2_anchor.jstree-anchor.jstree-grid-col-0 {jQuery210079930421616882090.3613452061545104: 21, charset: "", coords: "", href: "./treegrid2.html#", hreflang: "", …}
timeStamp: 1447634933721
type: "click"
````

What am I doing wrong with passing the event on to `click.jstree`?

**Comment by side-by-side** [comment]
Almost.
1. Yes. Simple click as implemented now.
2. Partially. On Ctrl-click in the tree column or **anywhere** in the grid row it should add the node to the selection or remove the selection.
Just like in jsTree demos: https://www.jstree.com/demo/
Try select several nodes using Ctrl.
With jstree-grid plugin we want the same behavior, clicking at any place in the row.
