### ISSUE TITLE
[npm] Latest available version is 3.2.4

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#121]
https://www.npmjs.com/package/jstreegrid

**Comment by deitch** [comment]
Ouch. Knew we forgot something. Just pushed out latest version.

**Comment by jochenberger** [comment]
Could it be that there's something wrong with the NPM releases? On https://www.npmjs.com/package/jstreegrid, the latest version is 3.4.6, but the latest version on GitHub is 3.4.4.

**Comment by deitch** [comment]
Huh. It looks like the tag didn't take on my laptop, so it didn't push out to github correctly. I will tag again and hope it works.

**Comment by deitch** [comment]
It did in package.son, if you look on github.

**Comment by deitch** [comment]
OK, looks like now it took. Thanks for pointing it out.
