### ISSUE TITLE
Click column to sort

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#125]
Feature request:
Click column name to sort the nodes by that column.
Clicking again would invert the order.

**Comment by deitch** [comment]
I have seen - and implemented - this sort of thing on grids many times. It was one of those sortable grids that was the original inspiration for jstreegrid.

But how would that work with a tree? The tree by definition has a sort and embed order. If I use the first tree in the example file https://github.com/deitch/jstree-grid/blob/master/treegrid.html and click to sort based on price, what happens with all of the child/parent relationships?

jstree itself has a sort plugin, but that sorts only among child nodes, which makes sense. How would it work here?

**Comment by adamjimenez** [comment]
Sort the parent nodes first, then sort the child nodes within the parents,
e.g. see:
http://dev.sencha.com/extjs/5.1.0/examples/tree/locking-treegrid.html

On 20 November 2015 at 05:14, Avi Deitcher <notifications@github.com> wrote:

> I have seen - and implemented - this sort of thing on grids many times. It
> was one of those sortable grids that was the original inspiration for
> jstreegrid.
>
> But how would that work with a tree? The tree by definition has a sort and
> embed order. If I use the first tree in the example file
> https://github.com/deitch/jstree-grid/blob/master/treegrid.html and click
> to sort based on price, what happens with all of the child/parent
> relationships?
>
> jstree itself has a sort plugin, but that sorts only among child nodes,
> which makes sense. How would it work here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deitch/jstree-grid/issues/125#issuecomment-158281634>.
>



-- 
Best regards,
Adam Jimenez

**Comment by deitch** [comment]
Good old ExtJS! I was contributing to the grids and trees there years ago. The original grid was one-way only; I added the first writable version called write-store, and the first dynamic scrolling grid dyna-grid. Some of that was the inspiration behind jstree-grid. It was so long ago that it predated github, actually was version controlled using svn, and Jack Slocum was still writing ExtJS.

I think that grid is pretty cool, but I don't see any point in doing it until the tree itself is sortable with that logic. 

@vakata any thoughts? Look at the link to http://dev.sencha.com/extjs/5.1.0/examples/tree/locking-treegrid.html

You can sort the tree. If you sort it it does it first by parent node, then by children within each node, then their children, etc. If it had the ability to sort like that, then I could look at grid-based sorting.
