### ISSUE TITLE
set_id causes duplicate cells

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#131]
Changing a node id causes duplicate cells for the same node.
I have a fix but it depends on a new set_id event in jstree:
https://github.com/vakata/jstree/pull/1298

**Comment by deitch** [comment]
I am a bit lost. What's the issue here? How can I replicate it?

**Comment by adamjimenez** [comment]
In my use case after doing a rename I run set_id on the node. We then need to clean up the columns which are using the old id. I need this to run after set id, so I have requested the event handler in jstree. I guess we could just over-ride set_id though if they don't add the event handler.

**Comment by deitch** [comment]
You rename the node using JS? The menu? Can you describe the steps?

Sorry to be obtuse, I just cannot see exactly what you are doing to reproduce it.

**Comment by adamjimenez** [comment]
After a rename event, I do:
```
instance.set_id(node, newname);
```
The old column cells are still around and when clicking on the node again it creates a new row of cells using the new id.

**Comment by deitch** [comment]
So you:

1. rename a node - either using JS API or the right-click menu - which changes the text content of the node. 
2. catch the `rename_node.jstree` event
3. call `instance.set_id(node, newname)`

Now what happens after you do? What do you mean "old column cells are still around"? Why would changing a node ID or name make column cells need to disappear?

Maybe if I had a fiddle that showed the scenario?

**Comment by adamjimenez** [comment]
The naming of the column cells is derived from the node id. So you end up having a div with id "jsgrid_oldid_col1", alongside "jsgrid_newid_col1"

**Comment by adamjimenez** [comment]
I've submitted a PR. The fix updates the classes/ ids and data attributes of the cells when the node id is changed.

**Comment by deitch** [comment]
I see the PR. I will pull it in in a few. I want to see the problem recur first.

**Comment by adamjimenez** [comment]
makes sense tho right?

to see the error, open the demo page and run these commands in console
```
$('#jstree').jstree(true).settings.core.check_callback = true
$('#jstree').jstree(true).set_id('j1_1_anchor', 'newid');
$('#jstree').jstree(true).edit('newid');
```

**Comment by deitch** [comment]
Yeah, I got it. I have a sample page running now.

So I don't love getting in the middle of `set_id` function, and there is a way to look at the node and get the original ID (every node keeps track of the original ID). But I am not sure if the headache is worth it compared to the straightforward override you provided.

**Comment by deitch** [comment]
Yeah, I tried the other way. Not worth the headache. Let's go with your way.
