### ISSUE TITLE
Grid row height depending on each node height

### ISSUE THREAD

**Issue by pavlo-tk** [deitch/jstree-grid#138]
Hello Avi.
This relates to my commit https://github.com/deitch/jstree-grid/pull/118.
I have implemented more one “thing” for a grid row line height calculation.
With the function below we can calculate the line-height of each row that will depend on each tree node (`<li>`) height. It is useful when the tree nodes has different heights (multiline contents).
Also with this we can remove setting default line-height for all rows from https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L242.

Take a look, maybe it is better option than we have now?
I didn't tested it with all jsTree functions, such as search. Maybe we will need more events to handle.

``` javascript
var initializeGridHeight = function($tree)
{
    $tree.on('ready.jstree refresh.jstree', function(event, data) {
        calculateHeight('#', data.instance)
    });
    $tree.on('open_node.jstree', function(event, data) {
        calculateHeight(data.node, data.instance)
    });
    $tree.on('redraw.jstree', function(event, data) {
        for (var key in data.nodes) {
            if (!data.nodes.hasOwnProperty(key)) continue;

            var node = data.nodes[key];
            if (data.instance.is_open(node)) {
                calculateHeight(node, data.instance)
            }
        }
    });

    var calculateHeight = function(node, jsTreeInstance) {
        node = jsTreeInstance.get_node(node);
        for (var key in node.children_d) {
            if (!node.children_d.hasOwnProperty(key)) continue;

            var childId = node.children_d[key];
            var nodeHeight = $('a#'+childId+'_anchor.jstree-anchor').outerHeight();
            var cellClass = 'jsgrid_'+childId+'_col';
            var $cell = self.$tree.closest('tr').find('td.jstree-grid-cell > .'+cellClass);
            $cell.css('line-height', nodeHeight+'px');
        }
    };
}
```

**Comment by side-by-side** [comment]
A bug found, closing for a while.

**Comment by deitch** [comment]
I am very confused. First this was an idea, then it was closed, then reopened?

**Comment by side-by-side** [comment]
I have closed it for a while to fix a bug. Current verision is working and i using it on my project.

**Comment by deitch** [comment]
OK, so please describe the issue. Are you saying that the PR 118 we did is incomplete?I thought 118 addressed multi-row nodes?

**Comment by side-by-side** [comment]
PR #118 calculates a row height once (first row) and set that height to all other rows.
This version calculates a row height for **each** row. It allows to have rows with different heights around a tree.

**Comment by deitch** [comment]
Hmm, I think I get this. So rather than on `ready.jstree`, calculate the height of the first row and apply it as a `<style>` to all `td.jstree-grid-cell`, instead calculate it on a row-by-row basis every time the tree is `ready` or a node is `redraw` or `open`. And then apply it to the individual cell, since each row can have a different height.

That it? If so, I like it.

Can you do 2 things?

1. open this as a PR
2. Include in the PR a test file in `tests/`, call it `variable-row-heights-test.html`, which would have 2 trees. One has constant row heights, the other has variable row heights. Easiest is to copy one of the existing files and modify.

**Comment by side-by-side** [comment]
Yes, you got it.
Ok, i will create a PR soon, in the new year :)
