### ISSUE TITLE
Error in Tree Grid 3.2.0 Demo

### ISSUE THREAD

**Issue by vsanandan** [deitch/jstree-grid#139]
I have basic knowledge in Javascript and wish to use jsTreeGrid for my project. When I'm trying to run TreeGrid3.2.0 given in Downloads as treegrid.html file,  I am getting the following error:

ReferenceError: require is not defined in jstree-3.0.8 : line 2.

I thought it was browser error then I included require.js to get next error similar to require (to include another file). I think there is an issue in including jquery.
jquery is included using:
<script type='text/javascript' src='http://code.jquery.com/jquery-2.1.0.js'></script>

Otherwise a working html file with proper include files (with their location) may help me. I need to include a contextmenu for the tree and edit option to grid elements should be made available by default.

This fiddle may be used to understand the issue.
https://jsfiddle.net/vsanandan/doj8qfff/1/

**Comment by vsanandan** [comment]
This fiddle may be used:
https://jsfiddle.net/vsanandan/doj8qfff/1/

**Comment by vsanandan** [comment]
After a lot of iterations, I could display the jstree with contextmenu options for the tree and edit menu option for grid elements. Still I have some issues to resolve: i)  I could create a new node in the tree. The grid shows corresponding column value empty. When I try to edit, it throws the error: "Uncaught Type error: Cannot read property 'value' of null     jstreegrid.js (570) ii) Unable to copy & paste tree nodes as new nodes to existing nodes. Kindly suggest ways to resolve these two issues.

**Comment by deitch** [comment]
I cannot even get your fiddle to run. Your links to external resources are all local, rather than to official jQuery, jstree, etc. resources.

Try this https://jsfiddle.net/doj8qfff/2/ and it works.
