### ISSUE TITLE
Issues with jstree 3.3.0

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#147]
See http://jsfiddle.net/3Lzr26bg/
The tree's "main column" is not visible. When the `grid` plugin is removed, the tree renders fine. The only difference I could spot is that the root node gets the `jstree-closed` CSS class.

**Comment by deitch** [comment]
Well, isn't that cute. How interesting. But I had no issues with another example with which I was working.

**Comment by deitch** [comment]
Yeah, it looks like it is the `jstree-closed` class, but not sure what it is.

**Comment by deitch** [comment]
Ok, now I see it. Definitely a jstree 3.3.0 thing.

**Comment by deitch** [comment]
@vakata help? From 3.2.1 to 3.3.0 it stopped working. It suddenly puts `class="jstree-closed"` on the tree `<div>`

**Comment by vakata** [comment]
Just added a fix for this - thank you.

**Comment by deitch** [comment]
Thank *you*, @vakata . Will this be 3.3.1 when released?

@jochenberger I am closing this out.

**Comment by jochenberger** [comment]
Thanks for your help guys.

**Comment by vakata** [comment]
@deitch yes, it will be v.3.3.1, I just need to close a RTL theme related issue and I will publish it.

**Comment by deitch** [comment]
Hi @vakata sorry to bug. Do you have a 3.3.1 ETA?
