### ISSUE TITLE
ui option to toggle columns on or off

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#157]
perhaps using a context menu

**Comment by deitch** [comment]
What does "toggle on/off" mean in this context?

**Comment by adamjimenez** [comment]
I envisage that you can right click a column and then see a menu with all the column names. You can then click the column name to show or hide it.

**Comment by deitch** [comment]
Reminds me of the ExtJS grids.

If you have any ideas, go branch and do a PR?

**Comment by adamjimenez** [comment]
Yes, that's what I had in mind

**Comment by deitch** [comment]
OK, please do. It should be an option, though; some people just do not want it.
