### ISSUE TITLE
Regression when using functions as `value`

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#158]
From https://github.com/deitch/jstree-grid/commit/f02f37a0b3f40945b1c9c502bdfed531241cee46#commitcomment-17430620:
>  As far as I can tell, it occurs when you have any columns after a column with a value function. As long as no columns have a value fn, or only one and it is the last column, it works. Else it fails.
http://jsfiddle.net/3Lzr26bg/4/

**Comment by deitch** [comment]
OK, I got it. There is a PR going in now for it.

**Comment by deitch** [comment]
Fixed by #159
