### ISSUE TITLE
grid uses .jstree-hovered in an incompatible way with jstree

### ISSUE THREAD

**Issue by srkunze** [deitch/jstree-grid#164]
jstree uses :focus when using the keyboard keys (up and down) whereas it uses .jstree-hovered for mouse hovering.

jstree-grid however always uses .jstree-hovered for both mouse and keyboard.

**Comment by deitch** [comment]
@srkunze I am having a hard time seeing it. I have a sample file, I use keyboard, I get `.jstree-hovered`, I use mouse, I get `.jstree-hovered`.

**Comment by srkunze** [comment]
I don't think so; at least when using the latest version. We have 5 different styles: selected, :focus, hover, selected + :focus, selected + hover. And they all look different.

**Comment by deitch** [comment]
I wonder if my test case is different than yours. Maybe throw up a simple fiddle, and in the fiddle itself (below the grid of course), some text in a `<div>` describing what steps to follow and what to look for?

**Comment by rlenders** [comment]
I don't know if [this fiddle](https://jsfiddle.net/ypmfoksa/) highlights the issue @srkunze is seeing, but dragging & dropping the selected row causes issues (at least in the latest Chrome).

![Screenshot](http://i.imgur.com/kTfW9Wh.png)

**Comment by rlenders** [comment]
[Adding checkboxes](https://jsfiddle.net/sdmtzbro/) makes it worse.

![Screenshot](http://i.imgur.com/dWjMrG6.png)

**Comment by deitch** [comment]
> Adding checkboxes makes it worse.

Worse = better!

The worse it is, the easier it is to see the issue, then reproduce it, then fix it.

But it will have to wait. Heading to Tokyo to LinuxCon. I am speaking on networking containers, with a special focus on ultra-low-latency environments. Interesting topic, and might lead to some new consulting or training.

**Comment by deitch** [comment]
I still don't get it. What exactly is the problematic behaviour? 

> Adding checkboxes makes it worse.

I just don't see anything strange. Can you lay out step-by-step:

* what actions you take in that fiddle?
* what results you see?
* what results you expect to see?

**Comment by rlenders** [comment]
In the images I shared you can see some misaligned blue cells below the "Price" column.
> what actions you take in that fiddle?
In the [fiddle with checkboxes](https://jsfiddle.net/sdmtzbro/), expand the root node, check both child nodes, uncheck the root node.
> what results you see?
The blue selection highlight background color under the "Price" column does not align with the actual selection.
> what results you expect to see?
Whatever is highlighted blue under the "Nodes" column should be be blue under the "Price" column. Selected nodes should have a blue background in all horizontal cells of the table.

**Comment by deitch** [comment]
Cool. That definitely should not be happening. :-)

BTW, it works the other way as well:

1. Expand the root node
2. Click the checkbox in the root node
3. All cells will be blue *except* for the `Price` in the child nodes.

**Comment by deitch** [comment]
OK, here is the root of the problem. We listen for the selection and deselection of a node at https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L389 and https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L394

However, if you select a parent, the event is passed *only* for the parent, and not for the auto-selected children. Similarly, if you select all of the children, and thus the parent is automatically selected, there are events for the children but not the auto-selected parent.

We need to ask for help.

**Comment by deitch** [comment]
@vakata can you help here? Ignore the long thread, here is the problem.

Look at the following jsfiddle: https://jsfiddle.net/sdmtzbro/

If I do the following:

1. Expand the root
2. Select (via checkbox) the root
3. The children are automatically selected as well

The above makes sense. 

But the `select_node` event is sent *only* for the parent, and *not* for the children. Thus, I have no way to know that the children were automatically selected.

Similarly:

1. Expand the root
2. Select all of the children
3. The parent is automatically selected because all of its children have been selected. 

The above also makes sense.

But the `select_node` event is sent *only* for the children, and *not* for the parent. Thus, I have no way to know that the parent was automatically selected. 

Is there a different event I should be looking for when a node is selected but not by human click?
