### ISSUE TITLE
Problem with opening selectBox

### ISSUE THREAD

**Issue by babolinGiordano** [deitch/jstree-grid#167]
Hello,
Thank you for your work with this plugin, is fantastic
Now i have a problem with three select box near all rows
When i try to click on it, the select it appears and disappear immediatly and i can't click on the selection.

this is my code:
[https://jsfiddle.net/by42m3vc/5/]

thank you for your help

**Comment by deitch** [comment]
> Thank you for your work with this plugin, is fantastic

Thank you! It is gratifying to hear. I just need to find a way to spend more time on it, as it cuts into my consulting and training hours.

I would like to hear how you are using it and for what purpose.

> this is my code:

I don't see any output with the jsfiddle. Just a blank screen.
