### ISSUE TITLE
Please add bower support

### ISSUE THREAD

**Issue by aadrian** [deitch/jstree-grid#168]
Please add Bower support to be able to publish it to the Bower repo: http://bower.io

Thank you.

**Comment by deitch** [comment]
Love it. It just needs a `bower.json` right? Feel like putting in a PR?

**Comment by aadrian** [comment]
here's a ```bower.json``` you could use:
```json
{
  "name": "jstreegrid",
  "description": "grid plugin for jstree",
  "main": "jstreegrid.js",
  "authors": [
    {
      "name": "Avi Deitcher",
      "url": "https://github.com/deitch"
    }
  ],
  "license": "MIT",
  "keywords": [
    "jquery",
    "jstree",
    "grid",
    "javascript"
  ],
  "homepage": "https://github.com/deitch/jstree-grid",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "jstree": "^3.3.1",
	"jquery": "^1.12.4"
  }
}

but you still need to publish it, use correct tags so that versions are set correctly, etc.
```

**Comment by deitch** [comment]
Similar to npm, right file, but need to publish. Is there an easy way to have it hook into github to publish to npm and bower when a tag is pushed?

**Comment by aadrian** [comment]
After setting a Tag in GitHub, and having configured the connection credentials:

1. ```%> npm publish```
2. ```%> bower register XXX```

should do the trick.

1. https://docs.npmjs.com/cli/publish
2. https://bower.io/docs/creating-packages/#register

There are of course "tutorials" how to do this too :) , e.g.:
https://sixtwothree.org/posts/publishing-packages-to-npm-and-bower
https://www.viget.com/articles/an-update-on-updating-npm-and-bower-packages

**Comment by deitch** [comment]
I `npm publish` all the time, and could do `bower` too. But you would be surprised how often it gets `git push ...` and we forget to do `npm publish`. Adding another just will make sure something is forgotten. Best is if I could do a Webhook.

Actually, even better would be a post-push hook. But, yeah, not dealing with it now.

Opening a PR, take a look and see that the bower.json is correct?

**Comment by deitch** [comment]
Never mind, I got it. No need for PR. I am setting it up and merging immediately.

**Comment by deitch** [comment]
Done
