### ISSUE TITLE
jsTreeGrid doesn't work with search plugin

### ISSUE THREAD

**Issue by jitianying** [deitch/jstree-grid#169]
Latest version jsTree and jsTreeGrid. After search, the following problems are shown:
1. Misalignment between "text" and "data" of a node.
2. After collapsing-and-expanding root node, the grid contents are gone. 

I will provide the source and data if needed.
Thanks,

**Comment by deitch** [comment]
Oh great. Another version mismatch? I've wanted this merged into jstree core for this exact reason.

**Comment by deitch** [comment]
Can you show how and when it fails?

**Comment by jitianying** [comment]
Please see attached html and json files.To make things clear: I have put json_id to both "text" and the first two columns of "data" so that the misalignment can be displayed.
To reproduce the problem:1. Right after the page is loaded, do a search "blast" for all columns, the result is as follows. (look at the json_id misalignment starting from the third line to the end). 
2. Now click the root to collapse:

3. Now click the root again to expand: (all grids except for the root are gone)

4. There are also misalignment errors/disappearing grids for the nodes in the middle of the tree, in addition to the root. But I think this can give you an idea.
Please let me know if I have anything neglected in my script. If there's a quick fix that would be great. Because I need to have this tool released soon.
Thanks,Tim 

    On Monday, August 15, 2016 7:42 PM, Avi Deitcher <notifications@github.com> wrote:
 

 Can you show how and when it fails?—

**Comment by jitianying** [comment]
Hi Avi,
What is the best version combination of jsTree and jsTreeGrid? I will be happy to use older versions if the grid and the search plugins work well with each other.

Thanks,Tim
 

    On Monday, August 15, 2016 10:23 PM, Tianying Ji <jitianying@yahoo.com> wrote:
 

 Please see attached html and json files.To make things clear: I have put json_id to both "text" and the first two columns of "data" so that the misalignment can be displayed.
To reproduce the problem:1. Right after the page is loaded, do a search "blast" for all columns, the result is as follows. (look at the json_id misalignment starting from the third line to the end). 
2. Now click the root to collapse:

3. Now click the root again to expand: (all grids except for the root are gone)

4. There are also misalignment errors/disappearing grids for the nodes in the middle of the tree, in addition to the root. But I think this can give you an idea.
Please let me know if I have anything neglected in my script. If there's a quick fix that would be great. Because I need to have this tool released soon.
Thanks,Tim 

    On Monday, August 15, 2016 7:42 PM, Avi Deitcher <notifications@github.com> wrote:
 

 Can you show how and when it fails?—

**Comment by deitch** [comment]
I'll try to get to this over next few days. I'm over 3G now, so not much ability to work with it. The limited bandwidth I have is dedicated to clients to whom I've committed.

**Comment by deitch** [comment]
As a general rule, I try to keep it up with the latest, but this is mostly pro bono - once in a while, someone really needs a feature or version support and hires me to take care of it for them - so often someone simply raises an Issue on github that some latest version combination doesn't work.

I have not had issues with 3.3.1 if I recall correctly. You had these issues with 3.3.2?
