### ISSUE TITLE
column sort requires resizable:true

### ISSUE THREAD

**Issue by QueroBartK** [deitch/jstree-grid#170]
With the Sort plugin and the grid plugin enabled. In order to be able to sort columns by clicking on the header you currently also need to set the resizable:true paramater in the grid settings. This feels like it doesn't make much sense as I don't see what sorting has to do with the ability to be resizable.

**Comment by deitch** [comment]
> This feels like it doesn't make much sense

No kidding. This seems so strange. Do you have a fiddle that demonstrates it? Two trees, both with sort and plugin, but one with resizable and one without?

**Comment by deitch** [comment]
I just managed to replicate it. How strange!

**Comment by deitch** [comment]
Running it through a debugger shows that the event handler never gets called at https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L637

... even though the header `div` has the correct class.

**Comment by deitch** [comment]
Aha!

**Comment by deitch** [comment]
Check out 3.5.22, pushed to git and npm.

**Comment by QueroBartK** [comment]
Ok, it seems that by the time I saw that you had posted some questions that you've managed to fix it. Good job 👍
