### ISSUE TITLE
Can't change empty values in dynamically generated grid

### ISSUE THREAD

**Issue by Zhivag0** [deitch/jstree-grid#171]
When try to change empty values in cell of **dynamically created grid** have error "Cannot read property 'xxx' of null".  Same error in test file **dynamic-root-node-test.html** Only possible to change value in first column, but not in second (empty values). Here is my demo: https://jsfiddle.net/71y3g4sk/1/
Is this features not implemented yet?
Thank you!

**Comment by deitch** [comment]
_Exactly_ what steps do you take to reproduce the error? Be as specific as possible. For example, how are you changing empty values in the `dynamic-root-node-test.html` file? I have no errors.

**Comment by Zhivag0** [comment]
When i change values of existing rows there is no errors. 
Error appear only if create new rows (dynamical). Your demo code dose not contains this possibility, but original jstree has, so i add this by myself. You can see your demo code here https://jsfiddle.net/71y3g4sk/1/ I change it only adding the ability to create new rows in grid.

**Comment by deitch** [comment]
Hmm, I think I see this. Is it that the `Edit` button does not work on any but the first column?

**Comment by deitch** [comment]
3.5.24
