### ISSUE TITLE
Provide jstree-3.3.0-patched.js for download

### ISSUE THREAD

**Issue by php1r** [deitch/jstree-grid#172]
By enabling dnd, it is necessary to use jstree-3.3.0-patched.js in order to make it work properly with jstreegrid. It would be greatly appreciated if this could be provided.

**Comment by deitch** [comment]
I had thought @vakata had fixed the issue in jstree, but just in case, here it is.

https://gist.github.com/deitch/a6926a4742bb0fc4979d87b168bec8ac

**Comment by deitch** [comment]
Yeah, looking at jstree-3.3.1, it looks like the patch is in there.
