### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by OgreTransporter** [deitch/jstree-grid#174]
I've a few ideas for new features:

1) context menu configuration
It would be nice to have an option to configure the context menu. I have to change the source code to set an icon and rename it to my local language. At jsTree I could overwrite the items by configuration.

2) disable edit feature for selected items
I would like to disable the editing feature for root elements. I would like to edit only the leaves.

3) matching data types
In HTML5 there are various new input field types like _number_ etc. (http://www.w3schools.com/html/html_form_input_types.asp). It would be nice to have an input field with type number, if I edit a numeric value.

**Comment by deitch** [comment]
Hi @OgreTransporter 

> 1) contextmenu configuration

Isn't that part of jstree as opposed to the grid?

> 2) disable edit feature for selected items

Again, isn't that jstree, as opposed to the grid?

> 3) matching data types

Do you mean for the grid or the tree itself? And can you give an example?

**Comment by OgreTransporter** [comment]
1) It's possible to configure the jstree context menu, but the contextmenu to edit the grid cells is hard coded: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L841
2) If the context menu of jsgrid is not hard coded, it is possible to word with the _disabled_ property to solve that issue.
3) I mean the grid cells. If the property is an integer or a float value it would be nice to have input fields with type number. A boolean value could displayed by a chackbox or two radio buttons.

**Comment by deitch** [comment]
> the contextmenu to edit the grid cells is hard coded

Good point. Yeah, that would make sense. We should follow the same style/API as jstree. How is the context menu configured there? I think you just have in the `jstree({/*...*/})` an item named `contextmenu` whose property is `items:{}`? I don't recall off the top of my head. Do you have a sample?

> If the context menu of jsgrid is not hard coded, it is possible to word with the _disabled property to solve that issue

Yep, agreed.

> If the property is an integer or a float value it would be nice to have input fields with type number. A boolean value could displayed by a chackbox or two radio buttons.

How would you configure that? What would a working example look like (albeit it won't work immediately)?

**Comment by OgreTransporter** [comment]
The contextmenu option is bind to jstree, so I use contextitems.

> How would you configure that? What would a working example look like (albeit it won't work immediately)?

I would add an option "datatype" to column configuration. If the option not exist or set to "text" everything is like now. If the option is set to "number", just add
```JS
"type" : "number"
```
to h2 in this._edit.
