### ISSUE TITLE
clicking on column invokes function twice

### ISSUE THREAD

**Issue by david9** [deitch/jstree-grid#175]
We have a treeview with two columns:
Column 1. Title 
Column 2. Button

Our Tree:
Root
 Title 1...........B1
 Title 2...........B2
 Title 3...........B3 

We have identified that for the first time tree is rendered and clicking on button works fine.
But when we expand any of the items, say Title 2, and clicking on button B2 invokes function twice.

I suspect that reason is below line:

``` javascript
last.click(cellClickHandler(tree,t,val,col,this));
```

It binds a click event to the column 2 twice. We should unbind event first then should be re-bound.

**Comment by deitch** [comment]
> I suspect that reason is below line:

Why would it do it twice? It should do it just once when rendering.

Can you put a sample on a jsfiddle? Seeing it actually fail makes it much easier to resolve.
