### ISSUE TITLE
data missing after search

### ISSUE THREAD

**Issue by QueroBartK** [deitch/jstree-grid#177]
I just noticed that searching in a tree with the following search options:
```
search: {
	show_only_matches: true,
	show_only_matches_children: true
}
```
with a search query that results in a node with children (the children do not answer the query requirements) will result in the tree showing the correct nodes but the child nodes that are shown because their parent was found will not have the corresponding data in the other columns.

(I was thinking of setting up a jsfiddle but I couldn't find an online link to the jstree-grid.js is there somewhere where I can find the latest version for use in jsfiddle or should I request an upload on cdnjs?)

before searching (data from demo but I've increased the size of the grid a bit):
![image](https://cloud.githubusercontent.com/assets/20296285/19069413/2b125010-8a27-11e6-81ba-4ec608f2d783.png)
after searching (the line in the search at the end is my cursor):
![image](https://cloud.githubusercontent.com/assets/20296285/19069426/3ecf6d86-8a27-11e6-9d86-f928a91b6b89.png)
filtering even further:
![image](https://cloud.githubusercontent.com/assets/20296285/19069503/8bb3dd62-8a27-11e6-8e30-4d2f03abe8a3.png)

You can clearly see that the node "GrandChild" is missing its data

**Comment by QueroBartK** [comment]
Not sure of or how I can contribute this directly (do I need to fork the project and then remerge projects? seems weird I would think that I'd need to create a new branch and and then commit that branch so you can review it and merge it with the master if it looks okay to you)

anyway around this point: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L413
you'd need to have something link this:
```
if(this._data.search.smc) {
	data.nodes = data.nodes.add(data.nodes.find('.jstree-node'));
}
```
(maybe it is cleaner to use a new variable instead of overwriting but you get the gist of it.)

**Comment by deitch** [comment]
> I was thinking of setting up a jsfiddle but I couldn't find an online link to the jstree-grid.js is there somewhere where I can find the latest version for use in jsfiddle or should I request an upload on cdnjs?

Definitely should request upload to cdnjs, but for fiddles, I just use the GitHub raw link directly.

**Comment by deitch** [comment]
> anyway around this point: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L413
you'd need to have something like this

I don't understand what you are changing here. Can you explain it?

**Comment by QueroBartK** [comment]
> > anyway around this point: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L413
> > you'd need to have something like this
> 
> I don't understand what you are changing here. Can you explain it?

sure. When the jssearch completes it will trigger the search.jstree event and will pass you the nodes it has found (so data.nodes are all the nodes that match the search query). currently you check the search settings to see if `show_only_matches` is true over here: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L409. (**S**how_**O**nly_**M**atches).

If this option is true you hide all data cells. then on https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L414 you'll add all parents of the matching nodes to the matching nodes and make each node visible.

What I do before this last statement is check if the  `show_only_matches_children` is true: 
```
if(this._data.search.smc) {
    data.nodes = data.nodes.add(data.nodes.find('.jstree-node'));
}
```
(**S**how_only_**M**atches_**C**hildren)

If this is true I'll add the child nodes with the class '.jstree-node' to the matching nodes.
That way when you get to the next statement you'll add the parents and show those data cells.

The only thing I'm a bit unhappy about is that in my example I just save the matching nodes + children back in the data object nodes property. I feel like it would probably be safer to use a new variable where you first put the matching nodes in and later can add the child nodes to (if the option is true)

**Comment by deitch** [comment]
> When the jssearch completes it will trigger the search.jstree event and will pass you the nodes it has found (so data.nodes are all the nodes that match the search query). currently you check the search settings to see if show_only_matches is true over here: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L409. (Show_Only_Matches).

> If this option is true you hide all data cells. then on https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L414 you'll add all parents of the matching nodes to the matching nodes and make each node visible.

Yes, correct, makes sense. I probably should do it the other way round - find each node and hide only those that do not match, rather than hide all and then show matches - but good enough for now.

> If this is true I'll add the child nodes with the class 'jstree-node' to the matching nodes.

So this just adds a previous step (could just as easily do it after), to add the children's cells as well, in addition to the matching row itself, which already is handled?

To some degree, I dislike replicating the show logic. I wish that `data.nodes` arg would return not just the matched nodes, but also all of the visible nodes. Then I don't need to search up or down for them, just add the cells for those nodes.

Conceptually, I like it. I think I want to change it slightly. Instead of adding children back and then matching rows' cells and parents, I would rather build one list and then add them. Same idea, just a bit cleaner.

> The only thing I'm a bit unhappy about is that in my example I just save the matching nodes + children back in the data object nodes property. I feel like it would probably be safer to use a new variable where you first put the matching nodes in and later can add the child nodes to (if the option is true)

Agreed completely. I am going to close this in a minute in favour of a PR, which I will flag you on.

**Comment by deitch** [comment]
> Instead of adding children back and then matching rows' cells and parents, I would rather build one list and then add them. Same idea, just a bit cleaner.

Never mind that. You already are doing that.

**Comment by deitch** [comment]
Closed in favour of PR.
