### ISSUE TITLE
fixedHeader always true

### ISSUE THREAD

**Issue by QueroBartK** [deitch/jstree-grid#178]
While browsing the code I saw the following line:
`fixedHeader: s.fixedHeader || true,`
This will always evaluate to true which doesn't seem like the goal.
Not sure why anyone would want to set this to false but now they don't even have the option.

I suggest replacing it with something like this:
`fixedHeader: (s.fixedHeader === false? false :  true),`

(I've tested both by just checking the value of fixedHeader by setting a breakpoint after it was set. I've not tested if the header is indeed not fixed when setting it false.)

**Comment by deitch** [comment]
No kidding. I wonder how that one ended up in there. Good catch.

**Comment by deitch** [comment]
3.5.23

**Comment by adamjimenez** [comment]
fixedHeader: s.fixedHeader !== false

**Comment by deitch** [comment]
Oh Lordy! This is what I get for cleaning up GitHub issues on jet lag (at LinuxCon/ContainerCon Berlin)

**Comment by QueroBartK** [comment]
@adamjimenez That is indeed a better way to write that. :)
