### ISSUE TITLE
layout discrepancy after upgrade to  0.98 - bug or not?

### ISSUE THREAD

**Issue by cimenta** [deitch/jstree-grid#18]
Hi 

could you please have a look at this issue I am having. I spent last two hours or so debugging it and I have no idea what else I can try.

I upgraded to the laters 0.98 grid and ... see  http://i.stack.imgur.com/b45a0.png the text "basics" that belongs into column filter is just after the node name. If I switch back to grid 0.95 everything is fine.

I tried to reproduce it on jsfiddle http://jsfiddle.net/radek/H9LQz/8/ assuming that it happens if columns before filter are empty but as you can see it works fine on jsfiddle.

If I delete all "float: left;" css setting that are in div's before the column filter "basics" will move where it belongs.

Any idea?

Thank you

**Comment by deitch** [comment]
And 3.4.0 has advanced beyond tables. I am closing this issue as "old version relevant only". If it shows up again and you can replicate with a fiddle, please reopen.
