### ISSUE TITLE
Search per column

### ISSUE THREAD

**Issue by QueroBartK** [deitch/jstree-grid#180]
@deitch  and I have been talking about this in issue https://github.com/deitch/jstree-grid/issues/146
I feel like this got a bit bigger than I first intended it to be and thus deserves its own issue.

Initial question:

> I'm wondering, are there currently any plans to allow column specific searches? this would result in an input field just below each header (for each column that is specified as searchable; maybe also at the bottom?) and maybe some optional parameters to override the search for specific columns or to override the default text input field to (for example) a combobox or something. (when used with sorting these search rows should stay in place!). This could potentially be used in combination with the current search method which searches over the entire grid.

We can split this question into two parts:
1) The API for searching per column
2) The GUI for searching per column

Ok, this is what I currently have for the first part:

https://gist.github.com/QueroBartK/c5494b569a0002d2ddf4b12458ad3aad

I've added it all in the function `this._initialize`. I did remove some functions from this gist as they weren't important to the search (so don't just copy paste over the existing code).

Note: I've not tested this with the ajax option of the search plugin. the ajax option might be problematic.

**Comment by deitch** [comment]
@QueroBartK thanks for making this its own issue.

**Comment by deitch** [comment]
I am trying to wrap my head around your V2 implementation. It looks like a lot of `initialize` scope vars that are used inside the function. It also looks like there is a `searchColumn` and `clearColumnSearch`, as well as various kinds of `search_callback` override.

Rather than reverse engineering the code (at least to start), mind describing:

1. What the API is? What I call for a regular search, what I call for a column, how they interact?
2. How it works under the covers?

**Comment by QueroBartK** [comment]
It is indeed a bit much I guess so I'll try to explain but if something is not clear feel free to ask. I'm not going to explain in the same order as the code as I hope it is clearer by explaining it in this order (but I might be wrong).

Ok, to start with I've added three public methods:
`searchColumn`
`clearColumnSearch`
`clearAllColumnSearches`

I've also added some internal variables to the init:
`columnSearch` boolean (default false)
`searchQueryPerColumn` string array
`currentSearchQuery` string array

I created another internal variable `omniSearchCallback` 
and i've overwritten the `search_callback`


So let me first get slightly into the `search_callback`, the `omniSearchCallback` and the `columnSearch`:

So during the initialization I'll save the original `search_callback` into the variable  `omniSearchCallback`.
Next if there was no `search_callback` set by the user I'll put your search function in the `omniSearchCallback`.

With this done I'll override the `search_callback`. It will now check the `columnSearch` variable which serves as a flag. if it is true it will use the column search and if it is false it will call the `omniSearchCallback`. So the `columnSearch` flag is a replacement of what I did before. Instead of always overriding the callback to search a certain column and then resetting the original callback I'll just set a flag to true and back to false.

Ok now I want to look at my the variable `searchQueryPerColumn`:
This will keep the last search string you've entered per column. So we'll first initialize this variable with an empty string per column as there was no search yet. when searching a column we'll save the string of that column in the index of the array that matches the column index. this array will always be the same size as the amount of columns.

The `searchColumn` method currently takes 3 parameters (with the last one being optional):
`text` the search string
`columnNumber` the index of the column to search
`narrowResultsOtherColumnSearches` optional boolean parameter defaults to true (can be changed). 

The method will put the search string in the `searchQueryPerColumn` array at the correct index.
Next it will  either put the  `searchQueryPerColumn` array in the `currentSearchQuery` variable or create a new array with only the search variable depending on the `narrowResultsOtherColumnSearches`. This is to give to option to search one column and one column only or to combine multiple column searches with an 'AND' to specify a specific filter.
Then it sets the `searchColumn` flag activate the `jstree.search` and once done searching deactivate the `searchColumn` flag

about the `currentSearchQuery`. This is the array that will be used by the `search_callback` when doing the column search. For every defined string in there (that isn't an empty string) it will call  `column.search_callback` (column in this case is a variable pointing to the column with the same index as the string index in the array).

Lastly during the initialization I loop through the columns from the settings and check if they have a function defined in their search_callback property. If this is not the case I create a default callback for a search on this column.

**Comment by QueroBartK** [comment]
A few notes I actually have written for myself:
It might be better to change `searchQueryPerColumn` and `currentSearchQuery` from an array to an object

instead of using `searchQueryPerColumn` to save the previous column searches for use as a 'AND' condition. It might be better to rewrite the `searchColumn` method to accept a object / array with index/value per column.

**Comment by QueroBartK** [comment]
Ok I've now taken the time to make an other implementation

I think it is cleaner than the previous one but it still uses a lot of the ideas established there.

I've removed the clear methods and the variables keeping the search state and changed the seachColumn signature.

The seachColumn now only accepts one parameter: searchObj. Which should be an object with key -> index of a column and value -> search value.

You can check the changes at this gist:
[https://gist.github.com/QueroBartK/9116c2ad66b7f37550f0dd0e224ee8bc](https://gist.github.com/QueroBartK/9116c2ad66b7f37550f0dd0e224ee8bc)

I've also made a fiddle where you can check it in action:
[example fidle](https://jsfiddle.net/ejkjq77k/6/)

Here I pasted the code of jsgrid in the fiddle with the changes of the gist as the changed version isn't hosted anywhere at the moment

**Comment by deitch** [comment]
Absorbing...

**Comment by deitch** [comment]
Wow. So finally read it (multiple times), and you implemented a lot more here than just "search per column." There is combined searches (logical `AND`) as well. And I prefer the second design.

I am not a big lover of global flags, although better than some other implementations, and we probably don't have much of a choice here given the search API.

Looking it through, but I think this should (soon) become a PR so we can do code review, comparisons, etc. and eventually merge it.

**Comment by QueroBartK** [comment]
yes, sorry I feel like my explanation might not be the best. If there are any questions that remain or anything that needs clarification feel free to ask and I'll do my best.

Anyway. with the second design, you mean the last one I posted right? As that is also the one I like the most. Incremental improvements :).

As for the logical `AND`. Yes it felt like the natural next step. I was also thinking of maybe adding something for a logical `OR` but that felt a bit too complex for now and I haven't quite figured out how this would work or how the API for it would look. I'm not even sure if we actually need a logical `OR`. At the moment `AND` should be enough.

Also note that at the moment the search callback can be overridden in the config for each separate column.

**Comment by deitch** [comment]
For logical `AND` and `OR` (and `NOT`, and everything else), have a look at https://github.com/deitch/searchjs ; it might give you some ideas (and even a usable lib).

**Comment by deitch** [comment]
So, let me summarize my understanding of the implementation:

1. When the plugin does `init`, it saves the user-provided `search_callback`; if not provided, save the previous default "search across the grid" one.
2. Create a flag called `columnSearch` that indicates if we are in a column search. Default to `false`
3. When the user does a `search`, it calls `search_callback`. Because `columnSearch === false`, it will just do the usual search.
4. When the user does a `searchColumn`, it sets the var `columnSearch` to the required search object and then calls `search()` for, well, anything, which will trigger `search_callback`. Because `columnSearch !== false`, it will invoke the special column-specific search. When done, set `columnSearch` to `false`, to avoid messing up the next search.

The actual search itself is implemented as a `search_callback` on each column, which is invoked from the _master_ `search_callback`. 

Is that a fair summary?

**Comment by QueroBartK** [comment]
> So, let me summarize my understanding of the implementation:
> 
> When the plugin does init, it saves the user-provided search_callback; if not provided, save the previous default "search across the grid" one.
> Create a flag called columnSearch that indicates if we are in a column search. Default to false
> When the user does a search, it calls search_callback. Because columnSearch === false, it will just do the usual search.
> When the user does a searchColumn, it sets the var columnSearch to the required search object and then calls search() for, well, anything, which will trigger search_callback. Because columnSearch !== false, it will invoke the special column-specific search. When done, set columnSearch to false, to avoid messing up the next search.
> The actual search itself is implemented as a search_callback on each column, which is invoked from the master search_callback.
> 
> Is that a fair summary?

That is correct.

> For logical `AND` and `OR` (and `NOT`, and everything else), have a look at https://github.com/deitch/searchjs ; it might give you some ideas (and even a usable lib).

looks interesting. I'll definitely look into it. I do have one question: How far do you think we should go with this? Do you have certain limits in mind for how far we should extend the searching functionality or is it more a case of "the sky is the limit".

**Comment by deitch** [comment]
> How far do you think we should go with this? 

As far as you have time for. :-)

Actually, it simply is a question of making an interface that works, doesn't break anything else, and is understandable by users. The latter often is hardest.

But let's take this a step at a time. Open a PR for just these changes, we add a test case file, merge it in, and then we can add more functionality, or improve it.

Hmm, you know, now that I think about it, I wonder if "searchColumn" is the right paradigm. Do users want to search _columns_ or the underlying _data_? Well, one step at a time. PR for this, get it in, then move on.

**Comment by QueroBartK** [comment]
> But let's take this a step at a time. Open a PR for just these changes, we add a test case file, merge it in, and then we can add more functionality, or improve it.

sounds good.

> Hmm, you know, now that I think about it, I wonder if "searchColumn" is the right paradigm. Do users want to search columns or the underlying data? Well, one step at a time. PR for this, get it in, then move on.
I'm guess you're right in saying that they want to filter the underlying data. However (and maybe I'm thinking about this wrong so correct me if I am) since this is a grid the underlying data is always divided in columns so does it make a difference?

Maybe this has something to do with the above point but I'm wondering if we should only allow the index of column as keys in the seachObject (or well the current version that only does logical `AND`) or also allow some sort of column name like you're examples in https://github.com/deitch/searchjs. It might be possible to use the column header as column name

**Comment by deitch** [comment]
> since this is a grid the underlying data is always divided in columns so does it make a difference?

Could be. But I think we are getting a bit ahead of ourselves. Let's get `searchColumn` indexed by column out there, then we can worry about more capabilities.

**Comment by QueroBartK** [comment]
Btw you probably noticed that for the callback per column I defined the signature as the following:
`function(str, columnValue, node, column)`. The default search will only use the first two parameters but I added the other two as I thought those might be handy for some people when implementing their own search. The question is if this is what we want or should I limit it to only the first two?

**Comment by deitch** [comment]
> The question is if this is what we want or should I limit it to only the first two?

In theory, I could think of a use case for that. In practice, we aren't using it now (it isn't referenced at all in the function), so why bother adding it?

So, going to open a PR? :-)

**Comment by QueroBartK** [comment]
^ There you go :-)

**Comment by deitch** [comment]
I am going to close this issue in favour of the PR.
