### ISSUE TITLE
Feature Request: column header input fields

### ISSUE THREAD

**Issue by QueroBartK** [deitch/jstree-grid#191]
Ok, With the latest version we have the ability to search a certain column. A next natural step to me seems to be adding the ability to easily add input fields to the column header (and maybe later also to footer). 

Now depending on the content of the column I'm expecting that the type of input field might vary (from numeric to a combo box with a list of possible values to none at all while other columns do have input fields).

To me this seems like a good way to add searching a column as you'd have an input field per column but I think that there might be cases where people want to use this for something else. So I'm guessing that this needs to be customizable or even done outside of the jstree-grid scope?

Also is it useful to add the ability to get multiple rows of input fields?

I feel like a basic case is quite easy but as I start thinking about the possibilities for customization it starts getting quite hard.

What are your thoughts. What should be done and what shouldn't be done?

**Comment by deitch** [comment]
My instinct here is to have this use the API, but not integrated with the header. I think the headers are what people use as headers. They don't want to block/change/confuse it. 

However, I do see why you might want that. So what I would suggest is 2 parts.

1. Use the new and powerful search API to search columns.
2. Have the ability to add a new search row to the grid, below the headers but above the grid itself. 

It can be turned on (show) and off (hide) via the API. 

Thoughts?

**Comment by QueroBartK** [comment]
> Have the ability to add a new search row to the grid, below the headers but above the grid itself.

For me this seems like it would then be part of the header but perhaps we just have a different definition of header. It would just be a second row in the header that stays at the top of the grid even if you scroll through the grid data. I guess you could argue about the design of those fields (should the background around the input box have the same color of the header, ...)

(hmm, I just realized that it header could mean the text above each column or , as I intended it, the block)

**Comment by deitch** [comment]
Yes, I think we are agreeing on the concepts but disagreeing on the nomenclature. 

The way the tree is constructed, each column is a `<div>`, and within that div, there is a `<div class="jstree-grid-header jstree-grid-header-cell">` for the "header", and multiple `<div class="jstree-grid-cell">` for each actual cell.

The simplest way seems to be to have the following:

1. An option in the config to provide "custom sub-header" cells that would go in our own added `<div>` (we need for jstreegrid to control the wrapping `div`). Yeah, needs a better name than "custom sub-header".
2. An API call that shows/hides the custom cells.

The customizer can then apply their own events as they see fit to that custom HTML.
