### ISSUE TITLE
Feature Request: Expanding on search functionality

### ISSUE THREAD

**Issue by QueroBartK** [deitch/jstree-grid#192]
Ok before we discussed adding more options to the column search functionality. Here it seems that we might be able to use your library: [https://github.com/deitch/searchjs](https://github.com/deitch/searchjs)

I haven't quite taken the time to get into the entire code but from what I can see it looks pretty good for our use. There are a few things that I do wonder:
1) How does the searchjs deepsearch function fit in the jstree-grid context?
2) If we do use this library how do we feel about jstree-grid being dependant on another library? Or would you keep basic search mechanics in jstree-grid and make searchjs just a compatible library (not sure how to do this)? Will people be okay with downloading an extra library or would this be included in the jstree-grid download?

question added after edit#1 + edit#2 restructuring question: 
If we expand our search with or, not, ... then it is possible to do complex searches in only the jstree column which are currently not available in jstree. So should we ask to also add this functionality to jstree?

thoughts?

**Comment by deitch** [comment]
> How does the searchjs deep search function fit in the jstree-grid context?

Not really sure. jstree-grid really is flat, so this may be overkill.

> If we do use this library how do we feel about jstree-grid being dependant on another library?

Not great. I would prefer if it were optional. If you plan on doing complex searches, then include it, else not. 

As it is, dependency management on the Web still is a mess, mostly resolved build-time with tools like webpack. It is not the end of the world to make people include it, but not everyone does work that way. And we would need graceful degradation if we are to use it. What if someone depends upon it and they didn't include it?

**Comment by QueroBartK** [comment]
>> How does the searchjs deep search function fit in the jstree-grid context?

>Not really sure. jstree-grid really is flat, so this may be overkill.

This was my first feeling too.
> Not great. I would prefer if it were optional. If you plan on doing complex searches, then include it, else not.

hmm, I guess we could try detecting if it was included. If it is then we'll use that otherwise we'll just stick with the current functionality. (will need to think about this a bit)

> As it is, dependency management on the Web still is a mess, mostly resolved build-time with tools like webpack. It is not the end of the world to make people include it, but not everyone does work that way. And we would need graceful degradation if we are to use it. What if someone depends upon it and they didn't include it?

yea, they are working on ways to improve it:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import unfortunately this hasn't really been implemented by most browsers yet.

**Comment by deitch** [comment]
> yea, they are working on ways to improve it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

Sort of. That is ES6 modules, which are great, but even node7 (released recently) doesn't support it due to fundamental differences between commonjs and es6 module structures, evaluation, etc. They are working towards it, but it is non-trivial. See https://hackernoon.com/node-js-tc-39-and-modules-a1118aecf95e#.myu9ah2pt

However, even ES6 import assumes that the modules are available "locally". In node and other server-side platforms (any other JS ones left?), that means on the local filesystem. In the browser, that means either:

1. Bundled up in some large package and the `import` wrapped and worked in exciting ways: webpack, 
browserify, jspm, etc. So even if every browser had ES6 modules, you still need some form of packaging.
2. Dynamic require, pretty much requirejs/AMD, which has its own issues.

**Comment by rocchidavide** [comment]
I have installed jquerygrid with npm (I'm using ES6 and Webpack): I don't understand how to import jstreegrid in my code
