### ISSUE TITLE
fill cells when jstree source is html

### ISSUE THREAD

**Issue by ilichevd** [deitch/jstree-grid#193]
Hello, deitch, and thanks for your work! I found your jstree plugin a week ago, and it look very nice and useful. In my project I already implement jstree, but now I realize that I need a tree-grid, so your plugin is a best way to achive this task. I use lazy loading to get subnodes in html from server when I click a parent node. I don't use js viewmodels on client, so I generate HTML-code on server side, get it on client and paste directly to the tree. Example of server answer (when parent node opens):

 `<ul>`
 &nbsp; &nbsp; `<li customAttr="28" class="jstree-leaf" data-jstree='{"icon":"house.png", "customAttr":"28"}'>`
                &nbsp; &nbsp; &nbsp; &nbsp;   `1111`
          &nbsp; &nbsp;    `</li>`
            &nbsp; &nbsp;    `<li customAttr="34" class="jstree-leaf" data-jstree='{"icon":"house.png", "customAttr":"34"}'>`
           &nbsp; &nbsp; &nbsp; &nbsp;         `123123`
           &nbsp; &nbsp;      `</li>`
       `</ul>`

I configure my jstree like this:

`$('.tree-container').jstree({`
  &nbsp; &nbsp; `'core': {`
     &nbsp; &nbsp; &nbsp; &nbsp; `'data': {`
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;    `'url': function (node) {`
     &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;            `...`
     &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  `}`
 &nbsp; &nbsp; &nbsp; &nbsp;`}`
 &nbsp; &nbsp;`},`
 &nbsp; &nbsp;    `'check_callback': true,`
 &nbsp; &nbsp; `'plugins': ["contextmenu", "grid", "dnd", "unique"],`
 &nbsp; &nbsp;  `contextmenu: {`
   &nbsp; &nbsp; &nbsp; &nbsp;   `select_node: false,`
  &nbsp; &nbsp; &nbsp; &nbsp;     `items: customMenu,`
  &nbsp; &nbsp; &nbsp; &nbsp;     `show_at_node: false`
 &nbsp; &nbsp;`},`
 &nbsp; &nbsp;`grid: {`
   &nbsp; &nbsp; &nbsp; &nbsp;  `columns: [`
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;      `{ width: 300, header: "name" },`
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  `{ width: 200, value: "customAttr", header: "customAttr" }`
 &nbsp; &nbsp; &nbsp; &nbsp; `]`
 &nbsp; &nbsp;`}`
`})`

What I see:

![see](https://cloud.githubusercontent.com/assets/23070164/19806623/c54f4664-9d24-11e6-81fd-727a5690df01.png)

What I expect to see:

![expect](https://cloud.githubusercontent.com/assets/23070164/19806635/dc2fb3a0-9d24-11e6-99bd-29250560ae01.png)

What am I doing wrong, and how shall I rewrite my code to get result? Thanks for answer!

**Comment by deitch** [comment]
Not really sure. Put in place a jsfiddle with it so we can see it happening live?
