### ISSUE TITLE
slideDown animation

### ISSUE THREAD

**Issue by srkunze** [deitch/jstree-grid#195]
jstree uses slideDown to close/open nodes. jstree-grid, however, dis-/appears immediately. Animation speed is controlled via the "animation" option in jstree.

**Comment by deitch** [comment]
It wasn't an issue in the early days, when grid just appended elements to each row in the tree. But the alignment was impossible, so we switched to a tabular grid, which meant animation has to be handled separately. 

Want to open a PR on it?
