### ISSUE TITLE
wholerow doesn't line up; second column dom order wrong

### ISSUE THREAD

**Issue by frumbert** [deitch/jstree-grid#200]
I have a jstree with ajax loading and a single extra column (jstree latest build - 9770c67). The row selection seems out of order for some (but not all) items. I'm not doing anything out of the ordinary with my code:

	var $TREE = $("#xmlTree").jstree({
	    'core' : {
	    	'themes' : {
		    	'dots': true,
		    	'icons': true
	    	},
	        'data' : {
			    'url' : function (node) {
		            	var parentId = ~~node.id.replace(/(page_|\#)/g,""),
		            		url = '/engine/loadnav/' + _courseid + '/' + parentId;
			            return url;
		        }
	        },
	        'check_callback': true
	    },
		'grid' : {
			'fixedHeader': false,
			'columns': [{"header":"structure","tree":true},{"header":"score","value":"score"}]
		},
		'plugins' : ['contextmenu','dnd','wholerow','grid']

![disparate dom positions](https://cloud.githubusercontent.com/assets/592257/20818007/1c635d1c-b87f-11e6-9355-cdb4aa537187.jpg)

**Comment by deitch** [comment]
Hmm, probably something in the logic of selection.

Can you put up a jsfiddle with the issue? If we can replicate it and look at the error happening, maybe we can get somewhere with it...
