### ISSUE TITLE
Initially selected nodes' cells are not selected

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#202]
See http://jsfiddle.net/mtfuhcw2/1/. Only the first cell in the "Child 1" row is selected, the others are not.

**Comment by jochenberger** [comment]
Also, if you click the row, all cells are selected correctly, but if you collapse and expand the tree now, only the first cell is highlighted again.

**Comment by deitch** [comment]
Yep, looks like it is a bug in `redraw_node`, which doesn't do the highlighting. It only does it on the `select_node` (and related events).

Hmm, is there a way to tell if a node is selected when it is drawn or shown?

**Comment by deitch** [comment]
Closing in favour of https://github.com/deitch/jstree-grid/pull/205
