### ISSUE TITLE
Grid not covering its parent div 

### ISSUE THREAD

**Issue by aditya1122** [deitch/jstree-grid#206]
Hi

I am putting the jstreegrid to a div and want the grid to spread through the parent div but its is not.

HTML Code:

```html
        <div class="col-md-10 col-md-offset-1">
            <span class="">Attribute Values:</span>
            <div style="overflow: auto; height: 300px; border-width: 1px; border-style: solid;">
                <div id="treeselectedvalues"></div>
            </div>
        </div>
```

JavaScript Code:

```js
                              $('#treeselectedvalues').jstree({
                        'core': {
                            'data': JSON.parse(data),
                            'force_text': true,
                            'check_callback': true,
                            'themes': {
                                'responsive': false
                            }
                        },
                        "checkbox": {
                            "keep_selected_style": false
                        },
                        "plugins": ["checkbox", "grid"],
                        //'plugins': ['state', 'dnd', 'contextmenu', 'wholerow']
                        // ,'plugins': ['wholerow']
                        "grid": {
                            "columns": [
                                { width: '40%', header: "Attribute" },
                                {
                                    width: '60%', header: "Value", value: function (node) {
                                        /*return (node.data.price);*/
                                        //if (node.id);
                                        if ($.inArray(node.id, $.map(module.projectTemporaryData.checkListData, function (v) {
                                            return v.value;
                                        })) > -1) {
                                            return ("<input type=\"text\" class=\"attribute_value\" data-attribute-id=\"" + node.id + "\">");
                                        }
                                        else {
                                            return;
                                        }
                                    }
                                }
                            ]
                        }
                    }).on('ready.jstree', function (e, data) {
                        module.loadAttributesData();
                    }).on("select_cell.jstree-grid", function (event, data) {
                        event.preventDefault();
                    });
```

Output Image:

![capture](https://cloud.githubusercontent.com/assets/16490922/21923985/f67565fc-d99c-11e6-9eae-f9f22543ca35.PNG)

I want the grid to cover the entire box.

**Comment by deitch** [comment]
Put a jsfiddle up so we can see it live?

**Comment by aaukt** [comment]
https://jsfiddle.net/6p9wwuxr/

Per documentation if no widths are given the grid should spread automatically across the whole container.

**Comment by deitch** [comment]
Wow. Long time later to come back to this.

**Comment by deitch** [comment]
Looks like `div.jstree-grid-wrapper` is expanding, but not `div.jstree-grid-midwrapper`

**Comment by deitch** [comment]
Right, well, that makes sense. Because `div.jstree-grid-wrapper` is just a `display:table-row`, so it wraps the cells/columns. Those would need to expand.

**Comment by deitch** [comment]
Lots of css magic here. I would be more than happy to take a PR on it, but not about to spend the next 24 hours messing around with the CSS.

**Comment by aaukt** [comment]
It is solved if you use
`.jstree-grid-wrapper {
    display: table;
}`

and set the grid wudth to 100%.

https://jsfiddle.net/6p9wwuxr/1/

**Comment by deitch** [comment]
That simple? OK.

**Comment by deitch** [comment]
No, it messed up a bunch of other things. Look at the tests, and try looking at `widths-test.html`. 

Like I said, the css for this is downright snarled. I am open to a PR, or if you can figure out how to get that to work without breaking the other widths, then move it in directly.

**Comment by aaukt** [comment]
It might not be a solution for all problems, but it is one for the sepecific problem in this issue that i also had.

For me personally it behaves better in most cases than it does currently, especially in cases with auto widths where you also see problems in the current `widths-test-html`.

**Comment by deitch** [comment]
> it behaves better in most cases

It probably does. If we can do that and fix the cases that it breaks in `widths-test`, I would be more than happy to make it default. Got time to figure out how to fix those?
