### ISSUE TITLE
open tree slowed down by grid

### ISSUE THREAD

**Issue by TZanke** [deitch/jstree-grid#211]
using a 1000 row tree takes around 150ms to open all nodes when clicking the "open" icon of the root node.

But after adding a grid, this process is slowed down massively, and adds another **2500ms**.
(see jstree-grid/tests/components/large-dataset-test.html)

![anim](https://cloud.githubusercontent.com/assets/1613368/22208163/303a7236-e182-11e6-81f6-bc2b4307ad64.gif)

**Comment by deitch** [comment]
Does your profiling show where in `_prepare_grid` the slowdown occurs? Which subset of it is slow?

I originally thought it might be rendering the nodes multiple times, but it actually does the render only if it is not already rendered.

I have some thoughts, but if you have some real data, it can be helpful.

I am creating a branch called `prepare-grid-perf` https://github.com/deitch/jstree-grid/tree/prepare-grid-perf to help with this. If it helps to break `_prepare_grid` into multiple functions so it is easy to profile, let me know.

**Comment by TZanke** [comment]
Quick update:

Most of the time is consumed by findDataCell. It is called 15.000 times in the large-dataset test when opening the root node.

**Comment by TZanke** [comment]
`_prepare_grid` has a [for loop](https://github.com/deitch/jstree-grid/blob/prepare-grid-perf/jstreegrid.js#L1007) which loops 3000 times, calling `findDataCell` **5** times each:

[L1062](https://github.com/deitch/jstree-grid/blob/prepare-grid-perf/jstreegrid.js#L1062), [L1107](https://github.com/deitch/jstree-grid/blob/prepare-grid-perf/jstreegrid.js#L1107), [L1109](https://github.com/deitch/jstree-grid/blob/prepare-grid-perf/jstreegrid.js#L1109), [L1111](https://github.com/deitch/jstree-grid/blob/prepare-grid-perf/jstreegrid.js#L1111), [L1112](https://github.com/deitch/jstree-grid/blob/prepare-grid-perf/jstreegrid.js#L1112)

### first loop:
Line 1: 0.040ms
Line 2: 0.046ms
Line 3: 0.079ms
Line 4: 0.030ms
Line 5: 0.023ms

### last loop:
Line 1: 0.400ms
Line 2: 0.220ms
Line 3: 0.207ms
Line 4: 0.159ms
Line 5: 0.192ms

**Comment by deitch** [comment]
Yeah, I had a suspicion it was that, thanks for proving it. Will try some patches soon.

Last loop is longer because of its serial nature. Nothing a little optimization and caching cannot help.

**Comment by deitch** [comment]
> 3000 times

For a 1,000-node tree? It should loop 1,000 times.

**Comment by deitch** [comment]
Yeah, `findDataCell()` is necessary to find the cell for a given combination of (`node`,`col`). But because it does the following search:

```js
ret = from.find("div["+NODE_DATA_ATTR+"='"+ids+"']");
```

It is doing an `O(n)` search. As the number of rows grows, so does the number of nodes to search, and it gets slower and slower.

Thinking of either having a hash lookup, or just looking by `id`. Both the `id` and the attribute `"data-jstreegrid"` are auto-generated from the same tree node object ID, but looking up by ID uses `document.getElementById()` which is *much* faster.

**Comment by deitch** [comment]
> It should loop 1,000 times

Or not. I see why it does 3,000 times. We can get it down by the # of columns, so that is a start.

**Comment by deitch** [comment]
@TZanke : Can you profile the latest commit to branch https://github.com/deitch/jstree-grid/tree/prepare-grid-perf again please?

I extracted all of the `findDataCell()` logic into one place and then used IDs. I still am using `find()` but it should be better performance nonetheless. `$(node).find("[attr]=val")` goes through every single descendant of `$(node)`, while `$(node).find("#someid")` _should_ use the DOM's `getElementByID()`.

Please post results here.

**Comment by TZanke** [comment]
Last git pull speeds up opening the root node from 2300ms to 1800ms. This is a **20**% speedup.

**Comment by deitch** [comment]
> This is a 20% speedup.

Nice start, not enough. I suspect the `from.find()` is insufficiently fast. The number of `getDataCell()` calls doesn't bother me, since the stack push/pop should be quick.

What does profiling show? Where is it slowing down? I assume somewhere in `getDataCell()`, but where/which fn calls?

**Comment by TZanke** [comment]
Looks same as in [my last comment](https://github.com/deitch/jstree-grid/issues/211#issuecomment-274484457)

Just everything 20% faster.

**Comment by deitch** [comment]
You still see the last loop running 10x as slow as the first? It shouldn't, it is using hashed lookups!

**Comment by TZanke** [comment]
Ok i see, **Line 2 & 5** are now at a constant speed but the three remaining lines still slowing down.

**Comment by deitch** [comment]
> Line 2 & 5 are now at a constant speed but the three remaining lines still slowing down

This definitely confuses me. Why should it? They basically are doing the same thing.

`findDataCell(column,someCellId,columnNumber)`

Anything else insightful out of the profiling?

**Comment by TZanke** [comment]
At the moment i tested following lines:
```
console.log("Next: Line 2");
console.time("Line 2");
gridCellPrev = findDataCell(dataCell,gridCellPrevId, i);
console.timeEnd("Line 2");
console.log("Next: Line 3");
console.time("Line 3");
gridCellNext = findDataCell(dataCell,gridCellNextId, i);
console.timeEnd("Line 3");
```

**Line 2 is fast, line 3 not**. But when setting a breakpoint in loop **2900**, the data nearly looks the same. Just a other id. But _slower_.

I tried to find something to start with. So i added a counter to `findDataCell` in the `$.each` of type `string`.
```
$.each(columns,function (index,col) {
	console.count("each "+ cellId);
	ret = ret.add(from.find("#"+ cellId + col));
});
```
From one of the first loops:
```
Next: Line 2
each jsgrid_child38_col: 13
Line 2: 0.154ms
Next: Line 3
each jsgrid_child40_col: 4
Line 3: 0.182ms
```

Around loop 2900:
```

Next: Line 2
each jsgrid_child982_col: 11
Line 2: 0.144ms
Next: Line 3
each jsgrid_child984_col: 2
Line 3: 0.330ms
```

_At the moment i really don't know if this shows anything._ 

But what i also see are this lines from one of the other `findDataCell`:

```
each jsgrid_NULL_col: 2963
each jsgrid_Root_col: 2974
```

But this could also mean the last column is reached.

At the moment i don't know why it's slowing down. But it does?!

**Comment by deitch** [comment]
I just pushed another change out to the branch. It may break other things, haven't done proper testing.

But it switches from searching under a particular `div` to DOM-wide ID-based selectors. This, in turn, should cause it to use 100% `getElementsByID()` under the covers, which is faster. 

See now and let us know?

**Comment by TZanke** [comment]
pulled your improvements, now it's reduced from **1800ms** to **1250ms**, another 30% performance gain. Nice.

**Comment by deitch** [comment]
That sounds like a very good start to me. Time sliced half. Still should be faster, but this is a very good start.

I am going to make sure we didn't break anything on the way (well, we did, but those already are fixed), then merge these in. We can continue to look for more improvements after.

Curious as to how you are profiling. Just using Chrome Debugger, enable "JS Profile", record open the root node of the tree?

**Comment by TZanke** [comment]
Most of the time i am using the chrome debugger tab _profile_, but also the _timeline_ tab is usable, because it shows a graph with e.g. loading, scripting rendering...

![image](https://cloud.githubusercontent.com/assets/1613368/22284416/8b0f66ec-e2e7-11e6-88d7-bd98f9ef13b2.png)


And as second i am using console.time() and console.profile() to get a time and/or a profile of a specific part of the code. See more at: https://developers.google.com/web/tools/chrome-devtools/console/console-reference

But yes, you are right, start record, click on the root node, wait, and then stop recording.

And do not miss the options in the profiling tab, this sometimes could also help finding the bottleneck: 
![image](https://cloud.githubusercontent.com/assets/1613368/22284601/526cb870-e2e8-11e6-91b8-20fe7437d5ca.png)

**Comment by deitch** [comment]
I am closing this in favour of the PR #213.

**Comment by deitch** [comment]
> Most of the time i am using the chrome debugger tab profile

That is what I was doing as well, but:

1. I didn't find the structure as intuitive as I would like
2. I didn't have the baseline with which you were working (system, etc.) so getting 1250ms on my system did not mean much.

Thanks!

**Comment by TZanke** [comment]
Just profiled the `_prepare_grid` again with my data to show the remaining bottlenecks.

![image](https://cloud.githubusercontent.com/assets/1613368/22323806/80f6bfa2-e3a5-11e6-8011-c01d4e25dc89.png)

**Comment by deitch** [comment]
Hmm, it looks like most of it is in the jQuery functions themselves. 

* `findDataCell()` is vastly improved by using `getElementById` (because of the direct `"#"` selector).
* `jQuery.append()` and `jQuery.after()` seem expensive, as do `filter()` `addClass()` and `trigger()`

We can look at making this better, but I suspect that the real improvement will come from using a shadow DOM, like React (which I will not implement here, but would consider a treegrid react component).

Any thoughts on your end?
