### ISSUE TITLE
tree disappears after closing node

### ISSUE THREAD

**Issue by TZanke** [deitch/jstree-grid#212]
The actual master does remove the tree after closing a node. This bug is probably introduced with #210 ?

![anim](https://cloud.githubusercontent.com/assets/1613368/22238800/b2e69638-e213-11e6-9611-43f153f33c03.gif)

**Comment by mindcreations** [comment]
Bug confirmed, same behaviour for me. Version 3.6.4 works, with 3.6.5 it behaves as @TZanke described.

**Comment by deitch** [comment]
Can you confirm it still exists in 3.7.0? We just introduced significant performance enhancements there, which forced us to do some clean up. I cannot reproduce it in Safari or Chrome.

**Comment by mindcreations** [comment]
Tried with v3.7.0, seems fixed, at least for me. Tried with Firefox and Chrome.

**Comment by TZanke** [comment]
Tested with 3.7.0, works

**Comment by deitch** [comment]
Sounds good to me.
