### ISSUE TITLE
date and version are not updated on version bump

### ISSUE THREAD

**Issue by TZanke** [deitch/jstree-grid#215]
See: https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L11
Compared to: https://github.com/deitch/jstree-grid/blob/master/package.json#L4

**Comment by deitch** [comment]
Yeah, I have wanted to put a proper build process in place for a while. `src/` directory with source files, builder, `make`, including inserting correct variable values.

Not convinced it is going to happen now, though. If there is an easy way to do it, happy to take a PR. :-)
