### ISSUE TITLE
Option state on grid after collapse/expand node.

### ISSUE THREAD

**Issue by izn** [deitch/jstree-grid#216]
https://jsfiddle.net/rq382sjg/1/

1. Open node;
2. Select option '1' on `<select>` in right grid;
3. Close and open node again;
4. Option '1' is not selected anymore.

It seems JSGrid ain't saving/refreshing the data **before** the close_node event.

Is there a way to _force_ JSGrid to save/refresh node data?

_(I don't think refresh the entire tree at every collapse/expand event is the best way)._

**Comment by izn** [comment]
Nah, nevermind.

I've found a solution and it isn't related to plugin (I guess). 
If you have same problem, you have to force-update the `data` attribute if you've dynamically updated some data/style in node.

Btw, in my case I've detected `select` doesn't update `selected` attribute when changing in pure html.

```
.on("ready.jstree", function (ev, data) {
  $('select').on('change', function() 
  {    
    // Weird?
    $("option[value=" + this.value + "]", this)
    	.attr("selected", true).siblings()
    	.removeAttr("selected");
    
    // Force-update data attribute.
    var outerhtml = $(this).parent().html();
    var node_id = $(this).parents('.jstree-grid-cell').data('jstreegrid');
    var node = $("#tree").jstree(true).get_node(node_id);
    
    node.data.select = outerhtml;
  });
});
```

**Comment by deitch** [comment]
There is more than just data persistence. In this case, your example has the value that it renders html:

```js
        		"data": {
      				"select": "<select><option value='1'>1</option><option value='2' selected='selected'>2</option>"
        		}
```

Even if jstree-grid had some form of data persistence, it would not be able to dig into your html and know it.

In the past, when we have had this, people have used external state engines and replaced your html with a function that renders html based on the state in the engine.
