### ISSUE TITLE
CSS need to applied to Jstree node based on condition

### ISSUE THREAD

**Issue by tssathish** [deitch/jstree-grid#218]
I have a json data below,

```json
data = [{ "id": 213, "text": "Apple", "parent": "#", 
   "data": { 
      "description": "Apple Fruit", 
      "parentName": "Apple", 
      "hasChildren": true, 
      "isDefault": true, 
      "isRequired": true, 
      "sortOrder": 1 
    } 
}, { "id": 216, "text": "Pine Apple", "parent": 213, 
    "data": { 
      "description": 
      "Pine Apple", 
      "parentName": "Apple", 
      "hasChildren": false, 
      "isDefault": true, 
      "isRequired": true, 
      "sortOrder": 1 
    } 
}, { "id": 220, "text": "Orange", "parent": 213, 
    "data": { 
      "description": "Orange", 
      "parentName": "Apple", 
      "hasChildren": false, 
      "isDefault": true, 
      "isRequired": true, 
      "sortOrder": 1 
    }
 }, { "id": 228, "text": "Custard Apple", "parent": 220, 
    "data": { 
      "description": "Custard Apple", 
      "parentName": "Apple", 
      "hasChildren": false, 
      "isDefault": false, 
      "isRequired": false, 
      "sortOrder": 1 
    } 
}]
```

Now I have following condition.

1. If **node.isDefault** then create checkbox - which is working.
2. If **node.isDefault** then apply CSS (background color to red) - this is not happening.

I am attaching the sample code, please help me solving the CSS issue.
please rename JstreeGRID.txt to JstreeGRID.zip

[JstreeGRID.txt](https://github.com/deitch/jstree-grid/files/768150/JstreeGRID.txt)

**Comment by deitch** [comment]
@tssathish I assume you are using `value: function(){...}` to set the value? 

Open a [jsfiddle](http://jsfiddle.net) where we can take a look at it live.

**Comment by tssathish** [comment]
@deitch Yes, you are correct. I am using value: function() {....}
1. To create checkbox based on condition (If the isDefault from data, then check box is created, which is working as expected )
2. My whole logic as expected is working but only one needed is as follows.

a. Jstree grid has 3 columns, first column has the tree 
b. 2nd and 3rd column will generate checkbox insise value :function {}....
c. based on the data, say for eg : if isDefault then the corresponding node in the first column has to be set some background color.

I am sorry @deitch, i tried setting the fiddle for my solution but i was not able to set that. thats y i have attached the sample project ("JstreeGRID.txt"), please rename JstreeGRID.txt to JstreeGRID.zip and extract the code. you will definitely get my logic. please help me on this getting done.

**Comment by deitch** [comment]
Sorry @tssathish I cannot download anything. Put your code up here properly formatted, see what can be done.

**Comment by tssathish** [comment]
Hello @deitch ,

I have uploaded the code here, please download all and run the html file. you will get it.

https://drive.google.com/drive/folders/0ByD5t6IJEcbiYUNpaUhfUno0cTQ?usp=sharing

Thanks.

**Comment by deitch** [comment]
You are applying the class before the node itself is rendered. When you run 

```js
var _nodeid = '#' + node.id + '_anchor';
var contrl = $(_nodeid);
contrl.addClass('nodebg');
```

The anchor has not yet been rendered by jstree. The only purpose for `value: function()` is to provide html that can be rendered. It isn't made for manipulating other parts of the tree. I suggest you use standard jstree events for that. https://www.jstree.com/api/#/?q=event

perhaps `redraw_node`?

**Comment by tssathish** [comment]
Hello @deitch ,

Yes I was trying to apply the CSS to the current being created. I though you guys would have faced it earlier. I am now working on the jstree events to fix this. anyways thanks for your valuable feedback, i will try working in redraw_node event.
