### ISSUE TITLE
title.replace ERROR

### ISSUE THREAD

**Issue by jjproe** [deitch/jstree-grid#219]
I have replaced in jstreegrid.js line 1062:

title = title.replace(htmlstripre, '');  ->  title = col.title.replace(htmlstripre, '');

**Comment by deitch** [comment]
I don't think that is correct. The previous line sets the `title` var correctly, this line just clears html out of it. See https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L1063

**Comment by jjproe** [comment]
[image: Inline-Bild 1]

2017-02-15 13:58 GMT+01:00 Avi Deitcher <notifications@github.com>:

**Comment by deitch** [comment]
No image there...

**Comment by jjproe** [comment]
Hello,

here is the screenshot from the Browser - Debugging...
"Uncaught TypeError: title.replace is not a function"

2017-02-15 14:32 GMT+01:00 Avi Deitcher <notifications@github.com>:

**Comment by deitch** [comment]
What browser?

Run it through a debugger, see what happens at that line. What is `title` set to? `string.replace` is very much a function, and the previous line should make it a string... unless you did something strange with the `title` property of that column or the data property of the particular row? Why don't you post the code here?

**Comment by cdigas** [comment]
You may force the title to be a string by adding:
title += '';
before the line
title = title.replace(htmlstripre, '');

**Comment by deitch** [comment]
Again, I don't understand your point. The previous line sets it, does it not?

**Comment by cdigas** [comment]
What about the situation where col.title is parsed as a number?

**Comment by deitch** [comment]
I didn't think it could, but that is fair. It certainly doesn't hurt. `title.replace` appears [here](https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L154) and [here](https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L1209)

A simple function like:

```js
stringreplace = function(input, pattern, replace) {
  return (""+(input === null || input === undefined ? "" : input) ).replace(pattern.replace);
}
```

And then replace each instance of `title = title.replace(htmlstripre, '');` with `title = stringreplace(title, htmlstripre, "")` should do it.

Open a PR for it, please.
