### ISSUE TITLE
Feature Request: Tree pagination

### ISSUE THREAD

**Issue by dustapplications** [deitch/jstree-grid#220]
Good day, your plugin is very helpful and we use it in our projects. I would like to have function where I can enable pagination on a tree just like DataTable do. Thanks and more power.

**Comment by deitch** [comment]
> your plugin is very helpful and we use it in our projects

Thanks. I would be most interested to learn what you are using it for.

> enable pagination

Does jstree itself support pagination? Without that, it is impossible to do. Unless I misunderstood you?
