### ISSUE TITLE
Stripes only visible on first column

### ISSUE THREAD

**Issue by Uezzi** [deitch/jstree-grid#221]
Hi,
I would like to see the rows of a jstree-grid an alternating colors, so I use the following jstree option:
$.jstree.defaults.core.themes.stripes = true;

But this works only for the first column, the remaining columns have no background.
![image](https://cloud.githubusercontent.com/assets/26411470/23906062/3875e21a-08cd-11e7-87f8-5cc520aa5902.png)

**Comment by deitch** [comment]
I suspect we don't pick up the stripes from the theme. Open a jsfiddle showing it?

**Comment by Uezzi** [comment]
Sure :-)
https://jsfiddle.net/gv3ho38w/

**Comment by deitch** [comment]
Yeah, now I see it. 

Nothing in the code currently supports picking up on the stripes from the jstree themes param. More than happy to take a PR on it and look at it, but unless someone brings one it, it won't get done. This project has no sponsorship. Going to close it, but very happy to take a PR. Interested?
