### ISSUE TITLE
error caused by this line of code ->if (obj && !this.is_hidden(obj)) 

### ISSUE THREAD

**Issue by lichanghuang** [deitch/jstree-grid#225]
Hi,

I'm using jstree-grid on top of an existing jstree in an MVC 4 application. I followed the instructions on how to use jstree-grid. I have 2 columns in my grid. One column is the tree structure and the other is a date time column. When I run my project this line of code causes a problem ->if (obj && !this.is_hidden(obj)). If I comment it out the code works fine.

**Comment by deitch** [comment]
Hi @lichanghuang . Can you put up a jsfiddle replicating the problem?
