### ISSUE TITLE
Merging cells for specific rows

### ISSUE THREAD

**Issue by asmpro** [deitch/jstree-grid#228]
Hi,

I would like to show a tree with two distinct types of rows (returned data).
Problem is that columns for these two types of data have different types and number of columns.
Because there are many columns, I would like to merge some columns into one (cell merging in excel) for row types with fewer column numbers.
As far as I can see this is not possible with the latest jstree-grid.
If I am right, will you consider implementing it or at least point me in the right direction?

Regards,
Uros

**Comment by deitch** [comment]
Um, wow? I cannot even visualize what you are trying to do. Do you have some kind of mock-up as to what it might look like?

**Comment by asmpro** [comment]
Hi,

I hope the following image explains it :)
![jstree-grid-cell-merging](https://cloud.githubusercontent.com/assets/7737396/25780731/6ae655d8-332d-11e7-809f-92ca5e025f50.png)

Regards,
Uros

**Comment by deitch** [comment]
I don't see how it is possible. The current structure actually is columns, with each cell a `<div></div>` in the column (and then the positioning calculated, which is complex, but worlds easier than pixel calculations where when it was horizontal `<span>` elements).

Hmm, I guess if you got an overlaid element just right?

Feel free to go ahead and try a PR if you want, but it is likely to be complex to get right. Or maybe get a client of my consulting (as opposed to free open-source) side to need it and get me to spend time on it? :-)

I will close out the issue, but if you find time to do a PR, that would be great and most welcome.

**Comment by asmpro** [comment]
Ok, thanx.

I will think about it.


Regards,
Uros
