### ISSUE TITLE
Still having problems with hidden nodes

### ISSUE THREAD

**Issue by PetzeltA** [deitch/jstree-grid#229]
If you load a tree with hidden nodes, the layout might be broken.
I've updated the repo: https://jsfiddle.net/qwnuaLm1/4/
The slight difference: some nodes have the state hidden.
If you open the vegetables node, the grid-items are not at their place.
This just happens when you load a grid with hidden nodes.
Btw. the tree is very slow if you have lots of elements. If you do not use the grid-plugin the tree gets much quicker, but that's another Problem. ;-)

**Comment by PetzeltA** [comment]
I think, that I found the solution!

The line 1018 (pos = $.inArray(lid, peers) is the problem, because some peers might be hidden.

The work around is:
Line 1018 should be changed to pos =0
After line 1021 (t= $(obj)) you need to insert this code:
var foundLID = false;
for (var i = 0; i < peers.length; i++) {
  if (lid == peers[i]) {
    foundLID = true;
    break;
  }
  if (!this.is_hidden(peers[i])) { pos++; }
}
if (!foundLID) { pos = -1; } //may be ommited

**Comment by deitch** [comment]
> If you open the vegetables node, the grid-items are not at their place.

It took me a bit to figure out what you meant. But I see that Aubergine should be $0.50 and Potato $0.20, rather than the other way around.

By the way, what *is* "Aubergine"? Sounds French?

**Comment by deitch** [comment]
> Btw. the tree is very slow if you have lots of elements. If you do not use the grid-plugin the tree gets much quicker, but that's another Problem

Yes. The performance has improved much over the years, but there always is room for improvement. Would be nice for someone to sit down and profile it with a large node set and see where it is running slowly.

**Comment by PetzeltA** [comment]
The code I posted yesterday just worked is some situations.
The real problem was the calculation of the previous-/next-/child-positions.
First a slight speed improvement
gridCellPrevId, gridCellNextId and gridCellChildId should be calculated outside the columns-loop.
So I moved them from the lines 1137,1139 and 1141 up to line 1037 - before the loop starts.
I now calculate the IDs like this to include the hidden nodes:
var prevPos = pos - 1;

				while (prevPos >= 0 && this.is_hidden(peers[prevPos])) {
				  prevPos--;
				}

				gridCellPrevId = prevPos < 0 ? objData.parent : findLastClosedNode(this, peers[prevPos]);
				var nextPeer = pos + 1;
				gridCellNextId = pos >= peers.length - 1 ? "NULL" : peers[nextPeer];
				while (gridCellNextId !== "NULL" && this.is_hidden(gridCellNextId)) {
				  gridCellNextId = nextPeer >= peers.length - 1 ? "NULL" : peers[++nextPeer];
				}

				var childPos = 0;
				gridCellChildId = "NULL";
				if (objData.children && objData.children.length > 0) {
				  while (childPos < objData.children.length && this.is_hidden(objData.children[childPos])) {
				    childPos++;
				  }
				  if (childPos < objData.children.length) {
				    gridCellChildId = objData.children[childPos];
				  }
				}

I will try to improve the performance if I can find some time.
Btw. aubergine is eggplant ;-)
Cheers

**Comment by deitch** [comment]
OK, let's think this through. The way it works now is:

1. Get my own tree node's ID as `lid`
2. Get all of the children of my tree node's parent's as `peers`
3. Find my position among my peers as `pos`

The above works only if all of my peers are visible. However, if one or more peers is not visible, my position will be correct on an absolute basis, but not on a display basis.

Is that it? 

If so, is the correct approach what you suggested here? Or should it render in the right position but hide the nodes?

**Comment by deitch** [comment]
> aubergine is eggplant ;-)

And that is why I didn't know it. I speak French, but I am allergic to eating eggplant, so it isn't in my usual repertoire. Once you said it, though, it rang a bell.

> First a slight speed improvement

I like this. It makes sense. Can you put in a pull request with the performance changes, and a separate one with the hidden-node fix changes? Let's keep them as separate resolutions.

**Comment by PetzeltA** [comment]
OK - I'll try. I am quite new to git - so I first have to read how to open pull requests. ;-)

**Comment by deitch** [comment]
It is really good to know - I use it both for open-source and for managing changes in large companies who are clients. 

I will save you some of the headache:

1. Fork this repository
2. In your copy, create a branch with a good name like "improve-performance-extract-columns-calc"
3. Make changes in your branch, commit, and push to your forked repo
4. Go to the home page for this repo (the original, not the forked copy). You should see an option for "create pull request" right at the top, highlighted in yellow. If not, just go to the PR tab and create one.

**Comment by deitch** [comment]
Closed by #232
