### ISSUE TITLE
In some searches, some grid cells that should be hidden are not

### ISSUE THREAD

**Issue by bragboy** [deitch/jstree-grid#236]
Hi,

When I try to hover over a node after I search for something, the equivalent hover is not appearing in place

![image](https://user-images.githubusercontent.com/1298587/32099367-a2aa4136-bb2d-11e7-99e5-1a76d8dfcaef.png)

Here is a the fiddle for the same: http://jsfiddle.net/bragboy/13Lgf90n/6/

To reproduce, just type for "flores" and hover as like shown in screenshot.

**Comment by deitch** [comment]
I don't get it. Do you mean hover, as in the title? Or do you mean the highlight of the cell in the next column?

**Comment by bragboy** [comment]
when you hover over the "Donna flores" in the example I've given, the equivalent highlighting is not appearing in the same row, instead it is in a different row as shown in the screenshot

**Comment by deitch** [comment]
And same problem if you hover over "James Gonzales".

**Comment by deitch** [comment]
And if you click them.

**Comment by deitch** [comment]
It isn't actually a hover problem. Trying adding data to the second column, you will see that it actually _does_ highlight the correct cell.

What it doesn't do is hide the previous cells correctly.

**Comment by deitch** [comment]
Try this. http://jsfiddle.net/13Lgf90n/7/

**Comment by deitch** [comment]
The bug appears to manifest when matches are descendants of 2 or more top-levels, in the 2nd and onwards top-level. Try searching for "Thomas" or "Gonzales".

**Comment by deitch** [comment]
Closed via #238

**Comment by bragboy** [comment]
Awesome! Thanks @deitch for the quick turnaround!
