### ISSUE TITLE
select_all.jstree Event is Not Handled

### ISSUE THREAD

**Issue by AhmadMaleki** [deitch/jstree-grid#239]
As said by jsTree API, `select_all()` method triggers two events:

- `select_all.jstree`
- `changed.jstree`

I see none of them being handled. So after calling the `select_all()` method, all jsTree nodes are selected but jsTree-Grid rows remain unselected.

**Comment by deitch** [comment]
If you put up a sample jsfiddle or similar, we can take a look. If you have a PR, even better.
