### ISSUE TITLE
Fix column order when using tree: true

### ISSUE THREAD

**Issue by jerrcs** [deitch/jstree-grid#240]
Issue #91 was implemented, however commit a423efbe32678940bf3ade0f86250762bc90c192 seems to break that functionality. Now the jstree column is always first, regardless of column order in the settings.

To reproduce, simply look at the 5th tree on the demo page (treegrid.html).

**Comment by deitch** [comment]
Oh yes, now I see it. Any ideas?

**Comment by deitch** [comment]
Interesting. If you look at the classes, they have the right ones, just are inserted in the wrong order.

**Comment by deitch** [comment]
Oh I see it. Looks like it detaches everything except the tree column, and then reattaches them. But if it detaches all except tree, and tree was index 1 (0-based) of 5, then when detach is done, tree has slid to index 0, so all reattaches put them _after_ the tree.

**Comment by jerrcs** [comment]
Can confirm it works now. Thank you for fixing this, much appreciated. 👍
