### ISSUE TITLE
Nodes do not respect width set on parent when initializing

### ISSUE THREAD

**Issue by pnoges-instartlogic** [deitch/jstree-grid#243]
Great plugin, it works wonderfully.  I actually use adamjimenez's fork of your plugin but I consider them very similar.

 I wont be able to share my full tree because its nodes load from a server, but for some reason that `stateful` config attribute doesnt seem to persist column width upon page refresh.  The grid appears fine. No js errors in the console. How should I begin troubleshooting why `stateful` is not working in Chrome and Firefox?  Those are the only browsers that I have tested this in.  None of the columns are persisting from a width perspective between page refreshes.

Using jstree 3.3.5
3.1.0/css/bootstrap.min.css
https://rawgit.com/adamjimenez/jstree-table/master/jstreetable.js
Note: Its based on your plugin. I couldn't get jstreegrid to work at all, but swapping "table" in for "grid" and using the jstreetable.js fork of your plugin seemed to work.  

```
table: { 
columns: [
{header: "Nodes", title:"_DATA_"},
{header: "(S) Status", value: "status"}, 


],

contextmenu: true,
fixedHeader: true,
resizable: true,
draggable: true,
sortable: false,
//width: null, //html5 storage of width via the stateful attribute doesnt work regardless of width being a value, null, or commented.
height: 2000,
stateful: true
},
```

**Comment by deitch** [comment]
`localStorage` is a `window` level property, so if it is enabled (it is possible to disable in most browsers IIRC), it should be stored. Did you open an inspector window after making a change to check the property is set? You can see the value [here](https://github.com/deitch/jstree-grid/blob/845a8950c1cb569fb328adecce5aea390039bae5/jstreegrid.js#L631). 

You also can do a page refresh, and check the `localStorage` then. Also might be worth seeing if the `rootid` for the tree got messed up. That would do it too.

**Comment by pnoges-instartlogic** [comment]
@deitch  in Chrome inspector how do i make sure localStorage is being set? 
Here is a 23 second high-definition screen recording demonstrating width resizing and how the DOM reacts.  Not shown, but the problem again is that page refreshing does not persist the widths.  Where do I go from here to troubleshoot window level property?   Thanks for the help!
Recording (download for High-Definition): https://gust.box.com/s/l41g67vr9yxybpvr7l4x3v9qmgtujov5

**Comment by deitch** [comment]
You need to open the console (just right click on the page and select "Inspect"), pick the "Console" tab, and you should be able to interact at will.

You would need to dig in there to find out what is going on.

**Comment by peternoges** [comment]
@deitch  hey Deitch, here is 15 seconds showing the issue.  I highlight the relevant part in the console.
Local Storage responds well to resizing columns, great. However, the value in local storage does not apply to the columns after page refreshing. As you can see in the video the page refresh makes the column larger than the value for it in localstorage.   How do we debug this from here?  Thank  you so much (download for HD quality) https://gust.box.com/s/xeo3o724z4aepk4mebp8atgj6zydwwwy

**Comment by deitch** [comment]
I just realized this remains open. 

I ran another test, same thing. The `localStorage` persists across both window refresh and closing the window and opening a new one. It both shows the value in the console when checking `localStorage` and does the right thing in the window. Tested on Chrome and Safari.

**Comment by peternoges** [comment]
Hi @deitch , 

We can close this issue. 

The problem actually seems to be CSS-related, from what I can tell.  The CSS that ships with jstreegrid seems to overrule the width that we would expect from localstorage.  In other words i think the css that ships with Jstreegrid 3.9.4 styles the "display" property of jstree-grid columns as "data-table", and for me this seemed to cause jstreegrid column widths to be non-stateful.

I was able to override jstreegrid 3.9.4 's  CSS in my own stylesheet, and after doing so the columns were stateful (obeyed localstorage width values)  For me this meant adding this CSS to my project:

```
div.jstree-grid-column {
    display: inline-block;
}
```

**Comment by deitch** [comment]
We used to talk about "DLL hell", but in the Web era, we discuss "CSS hell". Two steps forward, one step back. :-)

Why do you see the issue and I do not?

**Comment by peternoges** [comment]
I spoke too soon.  The workaround that I wrote about earlier sometimes causes alignment issues with the jstreegrid header.  To recap:  the current status of this github issue is that we are investigating why the issue appears in my project, but not for some other jstreegrid implementations.

**Comment by peternoges** [comment]
Update: still not sure why the issue happens in my project, but the "CSS solution" that seems to have no known consequences is the following:
```
div.jstreegrid-cell{
width:inherit;
}
```
without this, the browser ignored the width property that localStorage was writing correctly into the DOM.  With this CSS jstreegrid columns/cells now obey localStorage

I favor
```
div.jstreegrid-cell{
width:inherit;
}
```
over my previous hack#1:
`div.jstree-grid-column {
    display: inline-block;
}`
and over 
over my previous hack#2:
`div.jstree-grid-column {
    display: inline-grid;
}`

because both solve the localStorage display issue for me, but the previous hack#1 caused block-like wrapping  and previous hack#2 caused a seperator to dissapear

**Comment by deitch** [comment]
I am running tests to see if it works. In any case, I am going to rename this issue, since it isn't about html5 storage, but about respecting width from the parent.
