### ISSUE TITLE
How to edit a grid cell on double-click?

### ISSUE THREAD

**Issue by sfdctower** [deitch/jstree-grid#244]
Does jstreegrid support double-click cell editing (also known as inline editing) ? 

If not, maybe the solution is to listen for double-clicks on jstreegrid cells, 
or listen to double-fired select_cell.jstree-grid events (within a reasonably short amount of time).  
Once a double-click is detected, open the gridcontextmenu "edit" action
, and maybe display a fontawesome "pencil-alt" icon over the jstreegrid cell

Has anyone tried this?  
I think it would be valuable.

**Comment by deitch** [comment]
> Does jstreegrid support double-click cell editing (also known as inline editing) ?

Nothing inherent to it, but it wouldn't be all that hard. Just add a `dblclick` handler. I don't believe it would make sense without being able to have the same behaviour on the jstree itself, which defaults not to editing but to open-close the node, see [here](https://www.jstree.com/api/#/?q=click&f=$.jstree.defaults.core.dblclick_toggle)
