### ISSUE TITLE
Click function issue,  doubt its a selection problem, i think something is removing it?

### ISSUE THREAD

**Issue by sfdctower** [deitch/jstree-grid#245]
I am trying to fire an alert when someone initiates jstree grid sorting.   
I have been unable to get the alert to fire and have tried many selectors.
` $('div[class*=" jstree-grid-header"]').click(function(){`
and others.

As a final effort I right-clicked the first jstree grid column header and inspected it in Chrome.  I copied the selector and am wondering why the following code block still does not fire the alert:
```
$(document).ready(function() {
  $j('body > div.jstree-grid-wrapper > div > div.jstree-default.jstree-grid-column.jstree-grid-column-0.jstree-grid-column-root-jstree > div.jstree-grid-div-115-0.jstree-grid-header.jstree-grid-header-cell.jstree-grid-header-regular').click(function(){
  alert("click detected");
}
  });
```

It seems that the selector is the problem, or that my click function is being erased/removed when trying to attach it to your header because the following works just fine (some other selector on my page)
           $('body > h2 > a').click(function(){
                        alert("click detected");
                        });

**Comment by sfdctower** [comment]
I solved this by defining the click function within .on('ready.jstree' instead of  $(document).ready

**Comment by deitch** [comment]
It is more fundamental than it being overwritten. The way your selector was written:

```js
$(document).ready(function() {
  $j('body > div.jstree-grid-wrapper > div > div.jstree-default.jstree-grid-column.jstree-grid-column-0.jstree-grid-column-root-jstree > div.jstree-grid-div-115-0.jstree-grid-header.jstree-grid-header-cell.jstree-grid-header-regular').click(function(){
  alert("click detected");
}
  });
```

It adds a listener to `body > div.jstree-grid-wrapper > div > div.jstree-default.jstree-grid-column.jstree-grid-column-0.jstree-grid-column-root-jstree > div.jstree-grid-div-115-0.jstree-grid-header.jstree-grid-header-cell.jstree-grid-header-regular`, but that doesn't exist when `${document).ready`. By doing it at `.on('ready.jstree')`, you run it when it is rendered, so it works. 

I think having a standard event for sorting would be good, so you can just do:

```js
.on('sort.jstree-grid', () => {...});
```

Want to submit a PR?
