### ISSUE TITLE
How to call jstreegrid's edit button (grid._edit) from $( ".jstree-grid-cell" ).dblclick

### ISSUE THREAD

**Issue by sfdctower** [deitch/jstree-grid#246]
Great plugin. 

I use the `contextmenu ` config option, it gives me the ability to right-click and click "edit" to edit the jstreegrid cell.

How would I call jstreegrid's edit button `grid._edit(obj,col,target)` programatically on double-click?  The problem that I am having is that I dont know how to access `select_cell ` event parameters `event, data` in my `dblclick ` function.

I have intentionally set jstree's core option dblclick_toggle : false so that double clicks dont collapse / expand nodes.  I need help getting my `dblclick ` function to invoke `grid._edit(obj,col,target);`.  My attempts are in my subsequent posts below;  thanks in advance @deitch @jochenberger  for the help!

```
$("div#jstree").bind("loaded_grid.jstree",function(){
    $( ".jstree-grid-cell" ).dblclick(function() {
        alert( "The user double clicked a jstreegrid cell" );
		//How would I programatically call the jstree edit button from here?
    });

});
```

**Comment by sfdctower** [comment]
Still searching.  Again, clicking the gridcontextmenu's Edit button works fine but still unsure how to otherwise invoke jstreegrid's _edit function from within my dblclick function stated previously.
```
gs.gridcontextmenu = function (grid,tree,node,val,col,t,target) {
						return {
							"edit": {
								label: "Edit",
								"action": function (data) {
									var obj = t.get_node(node);
									grid._edit(obj,col,target);
								}
							}
						}
					}
```

**Comment by deitch** [comment]
>  I need help getting my dblclick function to invoke grid._edit(obj,col,target);. My attempts are in my subsequent posts below

People don't usually use double-click, specifically because of the core jstree double-click functionality. However, if you have disabled it, it seems reasonable to be able to double-click to do something. I don't know that we want to make a standard behaviour, but a standard way of capturing an event would make sense. So instead of:

```js
    $( ".jstree-grid-cell" ).dblclick(function() {
        alert( "The user double clicked a jstreegrid cell" );
		//How would I programatically call the jstree edit button from here?
    });
```

You would do something like the `select_cell.jstree-grid` but instead `dblclick_cell.jstree-grid`:

```js
mytree.on("dblclick_cell.jstree-grid", function(event, data) {
    if (/* some logic, if you want */) {
        event.preventDefault();
    }
});
```

Want to put in a PR for it? We would need to add the even to the README, but be sure to indicate that it only will work if the core `dblclick` functionality is disabled (as you did).

**Comment by charu12loks** [comment]
Hi ,

I have a JStree and a container with certain inputs on JSP page. i want to update the JStree with the values entered in the container.

i want to know how to fire edit event on jstree as first the cell needs to edit and then update. i need to invoke grid._edit(obj,col,target). but how to get reference to target and col.

**Comment by deitch** [comment]
Put up an example, @charu12loks
