### ISSUE TITLE
Issue when refreshing the tree (please hide appropriate grid data  upon "close_all")

### ISSUE THREAD

**Issue by sfdctower** [deitch/jstree-grid#247]
I'm calling  `$("#jstree").jstree("close_all");`

After all nodes collapse, I noticed that jstreegrid [does not clean up properly in response to the `close_all ` function
](https://gust.box.com/s/b7uq7vhkrieydtujqz0c1by2t0v616el)

Here is what happens after close_all is called: https://gust.box.com/s/b7uq7vhkrieydtujqz0c1by2t0v616el

Please update the following portion of jstreegrid.js so that `close_all` invokes `_hide_grid(data)`

Suggest editing this part of the code: https://github.com/deitch/jstree-grid/issues/57

**Comment by deitch** [comment]
> Suggest editing this part of the code: #57

Go for it. Please open a PR. Would look forward to it.
