### ISSUE TITLE
Problem using Html-Elements in gridrows

### ISSUE THREAD

**Issue by xNi-cOx** [deitch/jstree-grid#249]
Hi,

first of all, thank you for this project, it can solve one of my biggest problems.  
I want to use jstreegrid, to add additional custom data to the objects in my tree. For testing purpose i created one row which should display html input elements, but the result is not as expected.
I only got the html elements for the root elements of the tree. When i expand the tree no new input fields are displayed. Moreover the one which were there at initialization did not move down with the root elements.

As the screenshot shows, there are 7 input elements for the 7 root elements. They did not move with these elements on expanding and no new input elements are addeed.

![image](https://user-images.githubusercontent.com/37293161/40043082-b2416136-5823-11e8-9f66-d3d5eebee124.png)

I´m using jstree and jstreegrid within aps.net core. So here is the js code of my view:
jsTree 3.2.1
jsTreeGrid 3.9.3

`$(function () {

            $(".search-input").keyup(function () {

                var searchString = $(this).val();
                $('#treeview').jstree('search', searchString);
            });

            $('#treeview').jstree({
                'core': {
                    "themes": {

                    },
                    'data': {
                        'url':'/TreeView/GetRoot',                                
                        'data': function (node) {
                            return { 'id': node.id };
                        }
                    }
                },
                "checkbox": {
                    "keep_selected_style": false,
                    "three_state": false
                },
                "types": {

                    "Object": {
                        "icon": "glyphicon glyphicon-object-align-horizontal"
                    },
                    "Variable": {
                        "icon": "glyphicon glyphicon-ok"
                    }
                },
                "search": {
                },
                "grid": {
                    columns: [
                        { width: 400, header: "Nodes" },
                        {
                            width: 150, header: "TextBox", value: function (node) {
                                if (node.data.value == 'txtBox') {
                                    console.log("return");
                                    return ("<input type=\"text\" style=\"width: 120px;\" />" );
                                }
                            },}
                    ],
                    "resizable": true
                },
                 "plugins": ["checkbox", "search", "types", "search", "grid"]
            }).bind("loaded.jstree", function (event, data) {
                $(this).jstree("open_all");
            });`

The elements  displayed by jstree are generated with respect to an input and handed to the view in json.
I don´t know why it is only working for the root elements and not for all or on expanding. I´m hoping for some help and have to add that web development is not my main domain.

Thank you in advance :)

**Comment by deitch** [comment]
Hmm... can you out this up in a jsfiddle with it reproducing the problem? I don't have your source data here. It probably doesn't matter, but if you can put up a "working copy" (well, a "failing copy" :-) ), can take a look.

**Comment by xNi-cOx** [comment]
Okay i just created an example with jsfiddle. It doesn´t implement the whole functionality but shows the problem: https://jsfiddle.net/m6wazy2w/

**Comment by deitch** [comment]
OK, recreated. I know it worked at some point, so let's see where/how it broke.

**Comment by deitch** [comment]
I found it. You are using illegal IDs in the nodes:

```json
  {
    "id": "0;2253",
    "parent": "#",
    "text": "Server",
    "type": "Object",
    "data": {
      "value": "txtBox"
    }
  },
...
```

The IDs need to be legitimate html node IDs (or part of them), while `;` is an illegal character, which is causing lots of things to break.  See [this issue](https://github.com/deitch/jstree-grid/issues/123)
