### ISSUE TITLE
Jstree table Column width not working

### ISSUE THREAD

**Issue by ysumoh** [deitch/jstree-grid#250]
hi deitch,
column width 250 not working on column 'Price' and 'Qty'
here is the fiddle
http://jsfiddle.net/shmyusuf/56mxp4ov/2/

can you please assist

**Comment by ysumoh** [comment]
also the search is working only on First column, not on the second and third column.

**Comment by deitch** [comment]
Please open a separate issue on search.

**Comment by deitch** [comment]
> here is the fiddle
> http://jsfiddle.net/shmyusuf/56mxp4ov/2/

That fiddle doesn't appear to work?

<img width="1030" alt="screen shot 2018-05-27 at 11 06 53 am" src="https://user-images.githubusercontent.com/282526/40583809-57e1807a-619e-11e8-82de-e577547bc48c.png">
