### ISSUE TITLE
No warning if you forget the grid definition

### ISSUE THREAD

**Issue by ontoport** [deitch/jstree-grid#251]
instead jquery throws some weird error messages.
Proposal:
s.columns.length throws an error if s.columns is undefined.
Can be easily caught. Then issue an meaningful alert.
jstreegrid, line 222:

```js
        for (var i = 0, len = s.columns.length;i<len;i++) {
					if (s.columns[i].tree) {
						// save which column it was
						treecol = i;
						gs.treecol = treecol;
					} else {
            gs.gridcols.push(i);
          }
```

**Comment by deitch** [comment]
Sounds great! Why not open a PR?

**Comment by deitch** [comment]
Also, recommend using three backticks around code in the issue comments. I updated above.
