### ISSUE TITLE
How to update column's width when browser is resized?

### ISSUE THREAD

**Issue by sandraLaw** [deitch/jstree-grid#252]
Hello, good day!

How can I update each column's width in the grid when the browser is being resized? I know there is $(window).resize but i don't know how to get the jstree to change the column width after i recalculate the width for each column. It would be really great if you could provide some working lines. Thanks!

**Comment by deitch** [comment]
There is a `resize_column.jstree-grid` [event](https://github.com/deitch/jstree-grid#events) to notify you when a column width changes, but no API for changing it. Happy to take a PR for it.

**Comment by sandraLaw** [comment]
I see. Thanks for the feedback.

**Comment by sandraLaw** [comment]
I see. Thanks for the feedback
