### ISSUE TITLE
children of the opened node has disappear when opening other node

### ISSUE THREAD

**Issue by nandardevdjango** [deitch/jstree-grid#259]
![screenshot_2019-01-06 masterdata - user privilege](https://user-images.githubusercontent.com/36618360/50735111-cb6dee00-11db-11e9-97db-e4156f1b1aab.png)
![screenshot_2019-01-06 masterdata - user privilege 1](https://user-images.githubusercontent.com/36618360/50735116-d3c62900-11db-11e9-8ef2-e30d4e37b55c.png)

**Comment by deitch** [comment]
Can you give us a sample with this happening? The images are appreciated, but need to recreate it. A jsbin/jsfiddle/etc. if you can.
