### ISSUE TITLE
Problems with programatically generated nodes

### ISSUE THREAD

**Issue by omanthey** [deitch/jstree-grid#260]
Hello *,

I do have a jstree where I dynamically generate new nodes (a subtree) when a node is clicked using the jstree 'create_node'. 

How can I programatically fill the jstreegrid columns with the correct data, an how do I insert them into the right location. Currently the new grid elements are appended to the bottom of the existing grid and when closing th node again the added elements are not removed.

Is there any example I can fiddle with?

Best regards,
- Oliver

**Comment by deitch** [comment]
Hello @omanthey ,

jstreegrid _should_ pick up the new node, see the [code here](https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L452) which catches the event and re-renders. We have some tests that work on dynamic nodes ([here](
https://github.com/deitch/jstree-grid/blob/master/tests/components/dynamic-root-node-test.html), [here](
https://github.com/deitch/jstree-grid/blob/master/tests/components/rename-dynamic-node-test.html), [here](
https://github.com/deitch/jstree-grid/blob/master/tests/components/api-hide-show-test.html))  , but it is possible something is not working.

If you have a problem, put up a jsbin/jsfiddle/etc. including some of the code here and describing how to recreate.

**Comment by omanthey** [comment]
Hello @Deitch,

thx for the quick answer. After inspecting the given tests I'm pretty sure that the problem lies somewhere within my quite complex application logic ;-)

Thanks for giving us this great pice of software :-)
