### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by keshrath** [deitch/jstree-grid#264]
Maybe I made a mistake in the configuration, but most of the functions of this plugin don't work for me.

Showcase: https://codepen.io/keshrath/pen/XGgLgg?editors=1011

1. fixed header (should remain fixed when scrolling)
2. theme (theme should be the same for the grid)
3. contextmenu (contextmenu should be the same on the grid as on the tree)
4. wholerow (the sytle with wholerow is not transferred to the grid. it still has the style as without wholerow)

![image](https://user-images.githubusercontent.com/4851083/54084847-4e273c80-4336-11e9-9656-56d64e34920b.png)

**Comment by deitch** [comment]
Happy to take debugging information and suggestions for fixing.

**Comment by keshrath** [comment]
This will allow you to confirm that all the listed points are actual issues. Is there a version that worked? So the problems are due to a JS tree change?

**Comment by keshrath** [comment]
Any news on the issues?

**Comment by deitch** [comment]
Not really. This is catch-as-catch-can. I would be happy to see it fixed, if someone wants to contribute.
