### ISSUE TITLE
Problem with selectBox - flickers when click

### ISSUE THREAD

**Issue by tripti05** [deitch/jstree-grid#265]
Hi Avi,

Thank you for the awesome work with jstreegrid. Makes life a lot easier. I have implemented the same in my project. Everything works great except when I click the selectBoxes, it opens and collapses immediately, and i could not select the options. But when i double click it, it remains open and i can select the option. Below is my code. I have a working jsfiddle too. Can you please help me with this? 
[jsfiddle Link](http://jsfiddle.net/tripti05/039p5f2v/8/)
My code : 
`var jsonData =[{"id":"6345","text":"ActionType","parent":"6343","data":{"data_needed":"Y"}},{"id":"6343","text":"GeopoliticalInfo","parent":"6342","data":{"data_needed":"N"}},{"id":"6342","text":"BrunnelName","parent":"6267","data":{"data_needed":"N"}},{"id":"6267","text":"RoadElement","parent":"#","data":{"data_needed":"N"}},{"id":"6344","text":"GeopoliticalView","parent":"6343","data":{"data_needed":"Y"}}];`
 
`  var optionList =["Option1","Option2","Option3","Option4"];`

    $('#treeViewDiv').jstree({
    'core': {
	        'data': jsonData,
	        "themes":{"dots" : false}
	      },
	      "plugins": ["grid", "wholerow", "checkbox"],
		    	'checkbox': { 
					'tie_selection' : false,
					'whole_node' : false,
					 'three_state' : false
				},
				"grid": {
				columns: [
					{width: 214, header: "Attributes", 
       headerClass:"jtreeHeader", wideCellClass:"jtreeCell",title:"_DATA_"},
					{width: 110, header: "From", headerClass:"jtreeHeader", 
       wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								var sel_id = "from_"+node.id;
								return getOptions(sel_id);
					        }
					    },
					    title:"From"},
				    {width: 110, header: "To", headerClass:"jtreeHeader", 
      wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								var sel_id = "to_"+node.id;
								return getOptions(sel_id);
					        }
					    },
					    title:"To"}
				],
				"contextmenu":true,
				"resizable":true
				},
	     }).bind("loaded.jstree", function (event, data) {
	    	    $(this).jstree("open_all");
	  });
    
    function getOptions(id){
	  var combo = $("<select></select>").attr("id",id);
	  var option = new Option("--Select--", "");
	  combo.append($(option));
	   for (var i = 0; i < optionList.length; i++) { 
		   option = new Option(optionList[i],optionList[i]);
		   combo.append($(option));
	   }
	    return combo;
    }

Thanks in advance.

**Comment by deitch** [comment]
Will try to get to it, but quite overloaded for now. If you have any way of debugging it, it would help.
