### ISSUE TITLE
Add/Remove child nodes on click of parent nodes.

### ISSUE THREAD

**Issue by kaySharma** [deitch/jstree-grid#266]
I have a big JSON data which is for around 150Mb+ and I am facing the issue of jstree rendering.
I am not able to render a tree because of it. 
I was thinking to add or remove the child node on click of parent node when it is expanded or collapsed.
I am not able to find such events or might I have missed it.
So can you help me to know how to trigger a function on click of node expand and collapsed?

` $("div#jstree").jstree({
                        core: {
                            data: data
                        },
                        grid: {
                            columnWidth: 200,
                            columns: headers,
                            resizable: true,
                            draggable: false,
                            height: 700
                        }
                    }).on('loaded.jstree', function () {
                        $("div#jstree").jstree('open_all');
                    })`

**Comment by kaySharma** [comment]
May I get any update upon this if anyone knows how to trigger a function on click of node expand and collapsed?

**Comment by kaySharma** [comment]
I think there is no such solution?
May I get any update upon this if anyone knows how to trigger a function on click of node expand and collapsed?
Please revert back as It is too important for me to know.

**Comment by deitch** [comment]
Have you looked at the events from jstree?

**Comment by ViktorReib** [comment]
Why seen the basic Ajax example? It is realy easy to use. Or use close_node.jstree  open_node.jstree

**Comment by kaySharma** [comment]
@deitch & @ViktorReib Thanks for the help.

I was trying to use those events using 
`$("div#jstree").on('open_node.jstree', function() {$("div#jstree").jstree('close_all');})` 

But don't know why it doesn't work.

So have tried to bind the event using
$("div#jstree").bind("close_node.jstree", function() {$("div#jstree").jstree('close_all');});

It worked for me.
