### ISSUE TITLE
Clicking on node causes first column shift left in IE

### ISSUE THREAD

**Issue by sandraLaw** [deitch/jstree-grid#267]
Hello,

I recently come across jstreegrid and used it in my project. Everything works great except 1 issue with IE. I tested using my local machine and whenever i click on any node, the first column will shift to the left while the second column stays as it is. I tested using Chrome and Firefox but i don't get that issue. It's only with IE.

I have created a sample using [jsfiddle](https://jsfiddle.net/sandraLaw/01cmhuLn/8/). In the jsfiddle, I tried to click on the node at the first column but it doesn't show that issue. Try to click on the data on second column, you should be able to see the issue. Could you please kindly assist on this?

Looking forward to your reply. Thanks.

**Comment by deitch** [comment]
I actually do not have access to a machine with IE at present. I am curious as to which version of IE you found the problem, if it matters with earlier vs later.

**Comment by sandraLaw** [comment]
I see. Sorry, forgot to mention that my current IE version is 11.0.9600.19326

I just tried with Microsoft Edge and it seems like it doesn't have such issue...

**Comment by deitch** [comment]
IE11 is almost 6 years old (of course, the first version of Edge is just after that).

More than happy to take a PR for it and merge it in if it fixes and all passes, but not much more that can be done.
