### ISSUE TITLE
width in percentage instead of px

### ISSUE THREAD

**Issue by djangosdk** [deitch/jstree-grid#42]
Consider a scenario where jstreegrid is opened in dialog-box and when dialog-box is resized, jstreegrid  should adjust its columns according to new width of parent dialog-box.

I want grid columns to adjust on window.resize or if parent div is being resized , Grid should be able to adjust its columns widths in fluid/responsive manner.Can bootstrap help us with that ?
May be you can add support for percentage widths like
```
grid: {
        columns: [{},{},...,{}],
        width: "25%"
    },
```
Has anyone tried it with bootstrap classes ? Can anyone. Kindly do share experience.
Any ideas in this direction or may be i am missing something. Any help will be appreciated.

**Comment by deitch** [comment]
This actually works with the latest non-table-based version. Certain edge cases throw it off, like not defining the width and then having some percentage and some undefined widths, but overall it works.
