### ISSUE TITLE
Cannot make tree-node div set width

### ISSUE THREAD

**Issue by AndrewCranston** [deitch/jstree-grid#71]
I have set the column widths of the grid in my tree with jQuery thereby effectively making the tree fluid in width and taking up the full screen width.

However if the names of the first "name" column are too long the actual letters encroach onto the data columns....I have attached a screenshot that may make this garbled message make sense.

![jstree_hierarchy-issue](https://cloud.githubusercontent.com/assets/1695020/4131255/02403dd2-3344-11e4-8283-99700c02f837.jpg)

How do I go about truncating the content of the name column so that it observes a "text-overflow: ellipsis;" type of UI pattern?

Thank you

**Comment by deitch** [comment]
This has been untouched for a year. I am closing it out. If it still is relevant, take a look at v3.4.0 on, which eliminated tables entirely and uses a different overflow approach that might help. If not, reopen with a specific fiddle.
