### ISSUE TITLE
When changing a node with set_id, grid loses track of that item

### ISSUE THREAD

**Issue by ghost** [deitch/jstree-grid#85]
When I create a node it initially uses the generic ID that jstree makes. I then save that through ajax to a database and then return the ID back to jstree by using set_id. When this happens it seems the grid has no method to update the node in the grid.

**Comment by deitch** [comment]
@ghost This has been open for over a year with no comment. I am closing it out. If there still is an issue, please bring up a fiddle to demonstrate with the latest and comment here, and I will reopen.
