### ISSUE TITLE
using select and text boxes with jstree - grid 

### ISSUE THREAD

**Issue by tharasp** [deitch/jstree-grid#87]
Hi,

I am using jstree-grid for collecting prices for a set of items in database. I used alternate json for for rendering jstree:
jsonData = [{"id":1,"text":"Materials and varieties", "parent":"#","to_unit_name":"Kg","to_data_needed":"N","to_unit_id":"","to_active":"Y",},
{"id":2,"text":"Bricks","parent":"1","to_unit_name":"ml","to_data_needed":"N","to_unit_id":"","to_active":"Y"}, {"id":3,"text":"Class(Country burnt)(high quality)","parent":"1", "to_unit_name":"1000 Nos", "to_data_needed":"Y","to_unit_id":9,"to_active":"Y"}];

My grid rendering part goes like this:

"grid": {
"columns": [{width: 50, header: "Items", title:"DATA"},
{width: 30, header: "Unit", value:function(node){return(node.to_unit_name);}, title: "Default Unit"},
{width: 30, header: "Shop1 Price", title: "Price from Shop1", value:0},
{width: 30, header: "Shop2 Price", title: "Price from Shop2", value:0}],
"width": 25,
"contextmenu":true,
"resizable":true
}

But only jstree item list displayed in grid and values for columns 2, 3 and 4 not showing.

Also, I want to know whether i can place select and text boxes in jstree-grid.

Thanks.
![untitled](https://cloud.githubusercontent.com/assets/10546159/5771492/365a40ec-9d64-11e4-8c15-df35837d70df.png)

**Comment by tharasp** [comment]
I could place text box as
{"id":1,"text":"Materials and varieties", "parent":"#","data":{"to_unit_name":"<input type=\"text\" name=\"unitTreeTxt\" maxlength=\"15\">"},"to_data_needed":"N","to_unit_id":"","to_active":"Y",}.

Is it necessary to use "data" key for rendering cell values.

**Comment by deitch** [comment]
Will look at this over the weekend...

**Comment by deitch** [comment]
You have a few questions here.

> Is it necessary to use "data" key for rendering cell values.

As of now, yes. If you look at https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L592 you see that it takes it from `objData.data[col.value]` (and for the next 4 or so lines). It also does it for editing at https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L471 and https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L491

Now, there is no reason this could not be configurable, example have a config "dataField" which determines whether we look at `data` or anything else, with the default `data`. We could even include an option for `.` to stick to the object itself rather than a field like `data`. I would happily entertain a pull request for that. It should be pretty easy.

> Can I include select or text boxes in the grid?

Sure. The value of the field is treated as html and will be inserted as is. You could do it by putting the entire html into the value of the json, like you suggested, or just have the function generate it, as you did in the earlier example.

**Comment by tharasp** [comment]
Thanks. I could place text and select box with values inside grid. Now I want to retrieve values for selected nodes. The node data for selected ones was retrieved as 
```javascript
   var saveSchedule = function()
    {
        var selectedElmsIds = [];
        var selectedElms = $('#treeViewDiv').jstree("get_selected", true);
        $.each(selectedElms, function() {
            selectedElmsIds.push(this.id);
            alert(this.id);
        });
   };
```
Now how can I loop through respective grid columns for retrieving data from text box and select in association with node ids? 
Please help or hint any documentation on that.

**Comment by deitch** [comment]
Are you asking how you retrieve the current value of the cell?

**Comment by tharasp** [comment]
On a save button click, I want to retrieve the unit, shop1 price and shop2 price for all checked items. That is, I want to get ids of all checked items and then loop through it to fetch unit, shop1 and shop2 prices.

My jstree grid implementation is:
`$('#treeViewDiv').jstree({
							"core" : {
								"animation" : 0,
								"check_callback" : true,
								"themes" : { 
									"name": false, //default theme used
									"stripes" : true, 
									"variant" : "large",
									"theme": "default",
								    "dots": true,
								    "icons": true,
								    "url": false, // url of theme's css file
								    "expand_selected_onload" : true,
								},
								"data" : jsonData 
							},
							"types" : {
								"#" : { "max_children" : 1, "max_depth" : 5, "valid_children" : ["root"] },
								"root" : { "icon" : {"image":"../../jstree/themes/images/tree_icon.png"}, "valid_children" : ["default"] },
								"default" : { "valid_children" : ["default","file"] },
								"file" : { "icon" : "glyphicon glyphicon-flash", "valid_children" : [] }
							},
							"checkbox" : {
							      "keep_selected_style" : false,
							      "three_state"			: false
							},
							"grid": {
						        "columns": [{width: 40, header: "Items", headerClass:"jtreeHeader", wideCellClass:"jtreeCell", title:"_DATA_"},
						                    {width: 20, header: "Unit", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						        				value:function(node)
						        				{
						        					if(node.data_needed == 'Y') 
						        					{ 
						        						return("<select id=\"unitsSel_" + node.id +"\">" + getUnitOptions(node) +"</select>");
						        					}
						        				},
						        				title: "Default Unit"},
						                    {width: 20, header: "Shop1 Price", headerClass:"jtreeHeader", wideCellClass:"jtreeCell", title: "Price from Shop1", 
						        				value:function(node)
						        				{
						        					if(node.data_needed == 'Y') 
						        					{ 
						        						val = (node.shop1_price == 'null') ? '' : node.shop1_price;
						        						return("<input type=\"text\" id=\"shop1TreeTxt_" +  node.id  + "\" maxlength=\"15\" value=" + val + ">");
						        					}
						        				}						        					
						                    }, 
						                    {width: 20, header: "Shop2 Price", headerClass:"jtreeHeader", wideCellClass:"jtreeCell", title: "Price from Shop2", 
						                    	value:function(node)
						        				{
						        					if(node.data_needed == 'Y') 
						        					{ 
						        						
						        						return("<input type=\"text\" name=\"shop2TreeTxt_" + node.id + "\" maxlength=\"15\" value=" + node.shop2_price+ ">");
						        					}
						        				}		
						                    },
						                    {width: 20, header: "Remarks", headerClass:"jtreeHeader", wideCellClass:"jtreeCell", title: "Remarks,if any", 
						                    	value:function(node)
						        				{
						        					if(node.data_needed == 'Y') 
						        					{ 
						        						return("<input type=\"text\" name=\"remarksTxt_" + node.item_id + "\" maxlength=\"20\" value=" + node.remarks+ ">");
						        					}
						        				}		
						                    }],
						       
						        "contextmenu":true,
						        "resizable":true
						    },
						    "search" : {
						        "show_only_matches": false
						     },
							"plugins" : [ "checkbox","contextmenu", "dnd", "search", "state", "types", "grid" ]
						});`

and on save button click, I tried the following but unfortunately not working:

`var saveSchedule = function()
		{
			
			var selectedElmsIds = [];
			
			var selectedElms = $('#treeViewDiv').jstree("get_selected", true);
			$.each(selectedElms, function() {
			    selectedElmsIds.push(this.id);
			    alert(this.id + ";" + this.text + ";" + this.parent  );
			    alert($("#shop1TreeTxt_" + this.id).val());
			 });
}`

I have a set of problems/queries  here:
1. title for cells where text boxes and select boxes are placed do not get displayed.

2. I am placing an id for text boxes inside grid as shop1TreeTxt_" + node.id. But here an alert for node.id shows it as undefined. How can I get value of id field for this purpose? Except node.id, node.text and node.parent all other values under data key are fetching correct values.

3. Is this the correct approach to place text boxes / select boxes with different ids in grid cells?

4. Now in save part, can I retrieve values from text boxes and select boxes as they are from HTML elements?

**Comment by deitch** [comment]
Good to post the whole code. Should see if you can put it up in  plunkr or jsfiddle to give it a live example.

1. title for cells: The title is the value of the entry. Check out the README, look for the words "You can add a tooltip to each element". So you have `title: "Price from Shop 1"` which is not a value anywhere. There is not any support right now for just passing straight text to the `title` attribute, but that should be fairly easy. It is in LL625-629 of jstreegrid.js, if you want to put in a pull request. 
2. Alert for `node.id` is `undefined`: not sure about this one. Throw up a live example on a fiddle or plunkr so we can look at it.
3. Custom ID for input boxes: Sure, that is a good way to go. 
4. Save to retrieve values: There is nothing build into jstreegrid for it. I would do one of two things. Either have a callback (straight JS or jQuery) save it to the basic element on select. Or use the IDs to retrieve the value one clicking save.

**Comment by tharasp** [comment]
Hi,

I have demonstrated code in JSFiddle: http://jsfiddle.net/tharas/gw9ch970/43/

Here I have shown the problem mentioned in my previous mail. That is, node.id is alerted as undefined. I have solved this problem by repeating that field's value in JSON as item_id under data key.

I have another set of questions:

1. A click on any text box in the grid makes all other check box selections to disappear.

2. Each time I visit this page, my previous check box selections preserved. I felt keep_selected_style = false will solve this issue. But did not. You can see this by making some check box selections in the tree and by clicking again Run button. The previously made selections retained. 

How can I deselect all check boxes after grid loads. I tried the following code. But did not work.
    `$("#treeViewDiv").bind('loaded_grid.jstree',function(event, data)
    {
    $('#treeViewDiv').jstree(true).deselect_all();
    });`

**Comment by tharasp** [comment]
I could solve problem no. 2 with following statement in 'loaded_grid.jstree' event handler
`$('#treeViewDiv').jstree(true).clear_state();`

**Comment by deitch** [comment]
Yes, I was about to write that with the fiddle, I now understand your question about the ID. The `node` argument passed to `value` is the value of `node.data`, not the DOM object itself. So `node.id` doesn't really mean anything. But I see you figured that out. 

> click on a text box makes other check box selections disappear

This is interesting. When you click on a grid cell (it has nothing to do with your input box; same if it was just a blank cell), it calls `tree.deselect_all()` so that clicking on a cell is like clicking on a row, and only one is clicked. The revision is here https://github.com/deitch/jstree-grid/commit/dd2b19f18739d24fe043c2f82eb2fef322c036b4

Normally, without checkbox, you click only one row at a time. But the truth is, there are several scenarios:

* click: all other rows are deselected, that row is selected. This works fine.
* shift-click: select all rows from previous selection.
* ctrl-click: previous selections remain selected, add current selection
* checkbox: like ctrl-click, except if you click a parent node, in which case all children are selected/deselected

Right now, only the first case works fine. We would need either to add support for the other three cases, or more easily pass it up to the tree, if it works.

> Each time I visit this page, my previous check box selections preserved. 

No idea. This is a jstree question, isn't it? I think there is some jstree option to "reset all", but I cannot recall at the moment.

**Comment by deitch** [comment]
This works much better. Instead of trying to handle clicks, we just trigger the event, which causes jstree to do its right thing with it. Just pushed out to github (and npm of course).

**Comment by tharasp** [comment]
Thanks. As an easy solution, I just commented the line t.deselect_all(); in jstreegrid.js. Will it affect grid's functionality in an adverse way?

**Comment by deitch** [comment]
It will mess up clicking on a cell. But you don't need to bother with it. The change I pushed out earlier today to github and npm (version 3.1.12) fixes it.

**Comment by tharasp** [comment]
Unfortunately, version 3.1.12 does not work. updated fiddle http://jsfiddle.net/tharas/gw9ch970/45/
Seems like focus get switched to checkbox and textbox has no cursor.

**Comment by deitch** [comment]
Hmm, well, now I am at a bit of a loss. The 3.1.12 change definitely fixed the click/right-click/left-click/shift-click/etc. issue, but what we are seeing here is that the click on the input is being caught by the cell itself.

**Comment by deitch** [comment]
I think - but am not sure - that the click is being caught by the input box, then being propagated upwards to the cell, which is doing its own thing. Can you stop the event propagation in the `input` code?

**Comment by tharasp** [comment]
Updated fiddle http://jsfiddle.net/tharas/gw9ch970/61/ with stop event propagation for text box with label `Coarse`. I think the event is not getting captured.

**Comment by deitch** [comment]
The problem with your above fiddle is that you set up the click event *before* the DOM is drawn, so it has nowhere to attach it to. But doing it later will not necessarily help, since in a dynamic case, it might be drawn later.

The right solution is to catch it using `$("#tree").on('click',)`, but then you only catch the event after it bubbles up!

**Comment by tripti05** [comment]
Hi @tharasp ,

I am using jstree-grid implementation in the same way as you used in this issue. I am having problems in populating the dropdowns which are their in leaf nodes of my tree. Also, I want to know how did you save to retrieve the values from the select boxes while submitting the form. I want all the data in my controller when i submit the form.
Code:-

$('#jstree-mapping').jstree({ 
	    	 'core' : {
	    	    'data' : [{ "id" : "ajson1", "parent" : "#", "text" : "Simple root node","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson2", "parent" : "#", "text" : "Root node 2","data": {"data_needed": "N"} },
	    	        { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2","data": {"data_needed": "Y"} },]
	    	},
	    	"plugins" : [ "grid","wholerow","checkbox","sort" ],
	    	'checkbox': { 
				'tie_selection' : false,
				 'three_state' : false
			},
			"grid": {
				columns: [
					{"min-width": 110, header: "Attributes", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",title:"_DATA_"},
					{width: 110, header: "From", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=\"unitsSel\">" +getOptions(node) +"</select>");
					        }
					    },
					    title:"From"},
				    {width: 110, header: "To", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=" + node.id +">" + getOptions(node) +"</select>");
					        }
					    },
					    title:"To"}
				],
				"contextmenu":true,
				"resizable":true
				},
	     });
=================================================================
function getUnitOptions(node){
	  var options =[];
	  options.push("Merc");
	  options.push("Volvo");
	  options.push("BMW");
	  options.push("Jaguar");
	  for (var i = 1; i < options.length; i++) { 
		  $("#unitsSel").append($("<option></option>").val(options[i]).html(options[i]));
		}
  }
==================================================================

Quick help is appreciated!!

**Comment by tripti05** [comment]
Hi @tharasp ,

I am using jstree-grid implementation in the same way as you used in this issue. I am having problems in populating the dropdowns which are their in leaf nodes of my tree. Also, I want to know how did you save to retrieve the values from the select boxes while submitting the form. I want all the data in my controller when i submit the form.
Code:-
`$('#jstree-mapping').jstree({ 
	    	 'core' : {
	    	    'data' : [{ "id" : "ajson1", "parent" : "#", "text" : "Simple root node","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson2", "parent" : "#", "text" : "Root node 2","data": {"data_needed": "N"} },
	    	        { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2","data": {"data_needed": "Y"} },]
	    	},
	    	"plugins" : [ "grid","wholerow","checkbox","sort" ],
	    	'checkbox': { 
				'tie_selection' : false,
				 'three_state' : false
			},
			"grid": {
				columns: [
					{"min-width": 110, header: "Attributes", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",title:"_DATA_"},
					{width: 110, header: "From", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=\"unitsSel\">" +getOptions(node) +"</select>");
					        }
					    },
					    title:"From"},
				    {width: 110, header: "To", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=" + node.id +">" + getOptions(node) +"</select>");
					        }
					    },
					    title:"To"}
				],
				"contextmenu":true,
				"resizable":true
				},
	     });`
================================================
`function getUnitOptions(node){
	  var options =[];
	  options.push("Merc");
	  options.push("Volvo");
	  options.push("BMW");
	  options.push("Jaguar");
	  for (var i = 1; i < options.length; i++) { 
		  $("#unitsSel").append($("<option></option>").val(options[i]).html(options[i]));
		}
  }`

Quick help is appreciated!!

**Comment by tripti05** [comment]
Hi @tharasp 

I am using jstree-grid implementation in the same way as you used in this issue. I am having problems in populating the dropdowns which are their in leaf nodes of my tree. Also, I want to know how did you save to retrieve the values from the select boxes while submitting the form. I want all the data in my controller when i submit the form.
Code:-
`function getMappingTree(){
	  $('#jstree-mapping').jstree({ 
	    	 'core' : {
	    	    'data' : [{ "id" : "ajson1", "parent" : "#", "text" : "Simple root node","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson2", "parent" : "#", "text" : "Root node 2","data": {"data_needed": "N"} },
	    	        { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2","data": {"data_needed": "Y"} },]
	    	},
	    	"plugins" : [ "grid","wholerow","checkbox","sort" ],
	    	'checkbox': { 
				'tie_selection' : false,
				 'three_state' : false
			},
			"grid": {
				columns: [
					{"min-width": 110, header: "Attributes", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",title:"_DATA_"},
					{width: 110, header: "From", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=\"unitsSel\">" +getUnitOptions(node) +"</select>");
					        }
					    },
					    title:"From"},
				    {width: 110, header: "To", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=" + node.id +">" + getUnitOptions(node) +"</select>");
					        }
					    },
					    title:"To"}
				],
				"contextmenu":true,
				"resizable":true
				},
	     });
  }`

**Comment by tripti05** [comment]
Hi @tharasp ,

I am using jstree-grid implementation in the same way as you used in this issue. I am having problems in populating the dropdowns which are their in leaf nodes of my tree. Also, I want to know how did you save to retrieve the values from the select boxes while submitting the form. I want all the data in my controller when i submit the form.
Code:-
```$('#jstree-mapping').jstree({ 
	    	 'core' : {
	    	    'data' : [{ "id" : "ajson1", "parent" : "#", "text" : "Simple root node","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson2", "parent" : "#", "text" : "Root node 2","data": {"data_needed": "N"} },
	    	        { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1","data": {"data_needed": "Y"} },
	    	        { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2","data": {"data_needed": "Y"} },]
	    	},
	    	"plugins" : [ "grid","wholerow","checkbox","sort" ],
	    	'checkbox': { 
				'tie_selection' : false,
				 'three_state' : false
			},
			"grid": {
				columns: [
					{"min-width": 110, header: "Attributes", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",title:"_DATA_"},
					{width: 110, header: "From", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=\"unitsSel\">" +getOptions(node) +"</select>");
					        }
					    },
					    title:"From"},
				    {width: 110, header: "To", headerClass:"jtreeHeader", wideCellClass:"jtreeCell",
						value:function(node)
					    {
							if(node.data.data_needed == "Y") 
					        { 
								 return("<select id=" + node.id +">" + getOptions(node) +"</select>");
					        }
					    },
					    title:"To"}
				],
				"contextmenu":true,
				"resizable":true
				},
	     });
```
```function getUnitOptions(node){
		  var options =[];
		  options.push("Merc");
		  options.push("Volvo");
		  options.push("BMW");
		  options.push("Jaguar");
		  for (var i = 1; i < options.length; i++) { 
			  $("#unitsSel").append($("<option></option>").val(options[i]).html(options[i]));
			}
	  }```

Quick help is appreciated!! 
Tripti
