### ISSUE TITLE
grid not hiding node values for nodes hidden by search and show_only_matches

### ISSUE THREAD

**Issue by jrut127** [deitch/jstree-grid#88]
Hi, I'm using jstree-grid 3.1.10 and I've come across this issue.  I posted a stackoverflow question before I noticed this issues area so if you want, you can see it [HERE](http://stackoverflow.com/questions/28417163/jstree-grid-issue-when-attempting-to-show-only-matches)

Basically the issue comes up when using jstree-grid and the search plugin option of show_only_matches.  The matched items are shown and the other children at the same level are hidden.  However, those children that get hidden still have their grid values displayed.

Here is a fiddle that showcases the issue: http://jsfiddle.net/4102ydkj/
If you search for 1, 2, or 3 you'll see what I'm describing.

Also, here is a screenshot. Searching for test2 displays only the test2 children, but there are 2 tests under each of those schools and the information for the hidden tests is still being displayed.
![image](https://cloud.githubusercontent.com/assets/10928448/6113372/d8ad64ec-b064-11e4-839a-76b02d47a048.png)

**Comment by jrut127** [comment]
Just thought I'd update this with what I've done to get it working for me.  I just had to change the search function to hide the appropriate grid divs.

			$('#treeSearch').keyup(function () {
				if(to) { clearTimeout(to); }
				to = setTimeout(function () {
					var v = $('#treeSearch').val();
					$('#jstree').jstree(true).search(v);
					
					//hide/show grid values for nodes affected by searching
					var hidden = $('ul li:hidden');
					var visible = $('ul li:visible');
				
					$.each(hidden, function(i){
						$('div[id*=' + hidden[i].id + ']').hide();
					});
					
					$.each(visible, function(i){
						$('div[id*=' + visible[i].id + ']').show();
					});
					
				}, 500);
			});

**Comment by deitch** [comment]
Hey @jrut127 

Thanks for raising the issue. Let me see if I understand. When you search, e.g. in the jsfiddle for "2", you get the result "child2". Because you have `show_only_matches`, it shows just "Root" and the "child2", hiding "child1" and "child3". But the grid is showing the grid for all 3 children - "child1","child2" and "child3" - when it should just be showing the grid for "child2"? Is that it?

**Comment by deitch** [comment]
BTW, I updated your fiddle to include your solution here http://jsfiddle.net/4102ydkj/1/

And, you are right, hacking it from the outside is *definitely* a suboptimal solution. It should handle this correctly. Please confirm my understanding and we will figure this out.

May I ask what you are using it for?

**Comment by deitch** [comment]
OK, got it. Just used the same event `search.jstree` as jstree does when it is removing the unmatched nodes, and did our own grid logic on it. See 3.1.13, pushing out to GitHub and npm now.
