### ISSUE TITLE
Make it possible to insert columns to the left of the tree one

### ISSUE THREAD

**Issue by DRVTiny** [deitch/jstree-grid#91]
Hello, Deitch!

I think, it will be very usable to add possibility to place the jsTree content (tree itself) inside any column you wish, not only in the first column, which is hardcoded by default.
(In my situation i need to display some status information in a fixed (horizontal) position to the left of the node)

Thanks!

**Comment by deitch** [comment]
That is an interesting idea. I think the first step is to write what a sample config would look like that, then go to implementing from there. How would you view the config? And we should try to keep it backwards-compatible.

**Comment by DRVTiny** [comment]
I think that column with the title="__DATA__" must be the column contains
jsTree... And that column may be 1-st or 2-nd, etc.

Now special title value doesnt work at all: i can set title="__DATA__" for
5-th column but jstree-grid ignore this and moves jsTree to the first
column anyway.

2015-03-25 19:09 GMT+03:00 Avi Deitcher <notifications@github.com>:

**Comment by deitch** [comment]
I like it in principle, but I don't think `{title:"__DATA__"}` is the way to go about doing it. Why not just flag one of them?

````JavaScript
grid: {
	columns: [
		{width: 50, header: "Nodes",tree:true}, // <--- HERE
		{width: 30, header: "Price", value: "price", title: "price"}
	]
}
````

* If there is one node with `tree:true`, put the tree there
* If there is more than one node, put the tree in the first one
* If there is none, use the first column

I like it.

**Comment by DRVTiny** [comment]
I'm agree with you, it is very reasonable solution!
But... anyway, what to do with that strange and very unclear < title:
"__DATA__" > semantic? I think this could be removed from jstree-grid
completely...


2015-03-26 20:54 GMT+03:00 Avi Deitcher <notifications@github.com>:

**Comment by deitch** [comment]
It probably could, but not dealing with it today.

Fixed, pushed to github, published to npm, so it is all out. Also updated the demo with a fifth tree that supports is. Version 3.2.0. Enjoy.

**Comment by jerrcs** [comment]
FYI, commit a423efbe32678940bf3ade0f86250762bc90c192 seems to break this.

**Comment by deitch** [comment]
Do you know specifically what in [a423efb](https://github.com/deitch/jstree-grid/commit/a423efbe32678940bf3ade0f86250762bc90c192) ?
