### ISSUE TITLE
JSTree create_node with JSTreeGrid

### ISSUE THREAD

**Issue by tharasp** [deitch/jstree-grid#92]
I have placed a checkbox and select box in JSTreeGrid. When I create a new node in JSTree, I am updating html of cell span element with checkbox and select box. Pls see fiddle at http://jsfiddle.net/gw9ch970/78/. 
When I press return key on newly create node, both components vanish. What could be the problem?

**Comment by deitch** [comment]
Hmm, it is doing some sort of refresh that isn't saved, I think, but not sure.

**Comment by deitch** [comment]
No, correct that. Here is what happens, as far as I can tell:

# You click "Create Item"
# The `jstree.create_node` event is called, passing it the information. At this point, the node data model has the correct parent for where it will be, and the text "New Item".
# The jstreegrid handler for the `create_node` event is triggered, but it does not do anything. After all, the node is not yet in the tree, and so `this.get_node(data)` does not return anything
# The node is drawn in the tree, causing `redraw_node` to be executed. This is when the grid is first populated.
# When you click "Enter" or "Esc", the new node is drawn, executing `redraw_node`. Somewhere here or in between the previous event and this one, the elements are cleared from the grid,

**Comment by deitch** [comment]
OK, it has nothing to do with that at all. jstreegrid is never drawing your cell data for the new cell, your "Create Item" handler is doing it manually. jstreegrid expects to draw the value from the config property `value`, where you have the function. 

So when the edit is complete, the cell is redrawn, it goes to that `value`, and redraws the cell.

The reason it makes it empty, which is the same reason it isn't drawing it in the first place, is that the objData is empty when it calls `redraw_node`. Why that is, I do not (yet) know.

**Comment by deitch** [comment]
Ah, I get it. Because that is custom added.

**Comment by deitch** [comment]
It was calling the value function only if the node's `data` element was not `null` or `undefined`. When you create a node initially, it has `data` defined, e.g.

````JavaScript
				    "id": 1,
				        "text": "Materials and varieties",
				        "parent": "#",
				        "data": {
				            "item_id": 1,
				            "mal_item_name": null,
				            "data_needed": "N",
				            "def_unit_id": null           
				    }
````

When you create a new node dynamically, it doesn't have that, so it doesn't call the function value when it redraws. 

With the latest update 3.2.1, it calls it with the entire object info, including node data. Of course, you would need to populate the data or use the node directly.

See how I changed your example 

http://jsfiddle.net/gw9ch970/80/

**Comment by tharasp** [comment]
Thanks for the updates. I have no problem in including data part while creating new nodes dynamically. The solution at http://jsfiddle.net/gw9ch970/80/ works for the first time a new item created. For subsequent node creation, problems occur.
1. The new item name of previously created node does not get stored
2. When parent nodes switched, newly created nodes under previous parent removed.

**Comment by deitch** [comment]
Yeah, I see that, but I think that is a jstree problem, not a jstreegrid problem. Try it without the jstreegrid plugin enabled and see the problem still exists.

**Comment by tharasp** [comment]
Ok. solved issues with JSTree. Happy to see that I can render checkbox and select elements in grid while creating new nodes without adding code manually. Now I have another problem.

I create a new item and mark checkbox as selected and choose some option in select. Then I move this new node to another position. I see that checkbox selection gone and select option value reset.

**Comment by tharasp** [comment]
Sorry. Missed fiddle http://jsfiddle.net/gw9ch970/96/ for demonstration

**Comment by deitch** [comment]
I see you opened a new issue on that.
