### ISSUE TITLE
Grid element value reset problem in new node creation

### ISSUE THREAD

**Issue by tharasp** [deitch/jstree-grid#93]
Pls see http://jsfiddle.net/gw9ch970/96/ for demonstration. 

I create a new node and mark checkbox in grid as selected and choose some option in select box. Then I move this new node to another position. I see that checkbox selection gone and select option value reset.

**Comment by deitch** [comment]
That isn't surprising. When you drag and drop a node, it redraws the node. That, in turn, recreates the value inside the cell. In the case of this example, it will call the `value` function, which returns html:

````JavaScript
return("<select id=\"unitsSel_" + (node.data ? node.data.item_id : node.id) +"\">" + getUnitOptions() +"</select>");
````

To do what you want, you would need two things:

1. Store the checkbox state. 
2. Restore the checkbox state. 

These both are much easier to do with angular or other two-way binding frameworks, but you can easily just have a `.change()` handler to store it somewhere (I like the `node.data` on the node itself, but to each their own) and then set the value of `checkbox=checked` or not depending on the stored state.

**Comment by tharasp** [comment]
Sorry I was a bit slow in implementing solution as i was busy with some other assignments. 

Whenever I make a selection change, I store checkbox state in data part of json data by updating an attribute value `node.data.data_needed`. I use this attribute for rendering checkbox in grid with checked or unchecked state. 
Then use the following statements for refreshing jstree and grid with new json. 
    `$('#treeViewDiv').jstree(true).settings.core.data = jsonData;
    $('#treeViewDiv').jstree(true).refresh(); `

See updated fiddle http://jsfiddle.net/gw9ch970/108/

Without above statements, tree does not seem to redraw with new json data. With this, my checkbox selection does not get reset after a drag and drop. 

But the above statements makes the item rendering somewhat slow. Whenever user clicks on checkbox, entire tree disappears and appears again after 2-3 seconds. In real scenario, I have got around 400 nodes.

**Comment by deitch** [comment]
Refreshing the entire tree is going to be slow. You sure you don't want to go down some 2-way binding route? Angular, Ember, a bunch of others do this.

**Comment by tharasp** [comment]
Our project is nearing completion and probably not interested in including any new frameworks. In jstree, I found `refresh_node` method which will refresh only one node. But this method is not affected by changes in `node.data` part and hence the grid. Is there a method in jstreegrid so that i can refresh only the required node.

**Comment by deitch** [comment]
I can kind of see that. Just finished another project in Rails, really would have been nice with Angular or even better Web Components / Polymer, but no way was I going to change it then!

Where does the checkbox state get saved? You should do it on the actual check event. Put a `$("#treeViewDiv").on()` to catch changes to checkboxes and save them to the correct `node.data`. That in turn will allow the `value()` function to work automatically.

**Comment by tharasp** [comment]
I attach a `checkbox` `click` event handler with each `checkbox` in the grid in `ready.jstree` event handler. The `checkbox` `click` event handler function `handleCheckBoxClick` updates respective json data part  property `data_needed` to Y or N based on whether checkbox state is checked/unchecked. While rendering grid, I use this property for checking/unchecking checkbox. 

But after a drag and drop, the grid renders based on old json. Pls see fiddle at 
http://jsfiddle.net/gw9ch970/122/

    
    function handleCheckBoxClick(cb)
    {
        var checkboxid = cb.id;
        var itemId = checkboxid.substr(checkboxid.indexOf('_')+1);
        //Store checkbox state by updating tree's json data
        $.each(jsonData, function() 
        {
            if(this.id == itemId)
	    {
                this.data.data_needed = ($("#dneed_" + this.id).is(":checked"))?'Y':'N';
                console.log(this.text + '..' + this.data.data_needed);
	    }
	});
    }

**Comment by deitch** [comment]
I don't think that the original `jsonData` structure is referenced going forward; it is just loaded in. You would need to change the data store on the actual node.

http://jsfiddle.net/4cph9pku/

**Comment by tharasp** [comment]
Thanks. It's is working now.
