### ISSUE TITLE
Rendered data aren't in correct row

### ISSUE THREAD

**Issue by marmie1** [deitch/jstree-grid#94]
Hi,

I'm having a problem with rendering data. My application queries data correctly but it renders data to grid incorrect. It might have totally different information in columns that it should have. Any workarounds for this?

Thank you!

**Comment by deitch** [comment]
A sample of code that isn't working, please? A jsfiddle or plunkr would be far better.

**Comment by marmie1** [comment]
http://plnkr.co/edit/OG672jGYmfTjNSrrQZn3?p=preview

I cannot use real data but it's similar in that sample code. But around 100 rows. It actually worked in Plunker perfectly but not in my application. And there are no differences in rendering phase :D Weird. Data is passed as JSON like in Plunkr sample. Can you find anything else incorrect in that code snippet?

**Comment by deitch** [comment]
It looks pretty clean, and definitely works on the plunkr. 

I will close the issue, but if you manage to reproduce it, try to capture the actual JSON data into a file (maybe scrub it if there is confidential information) and then modify the plunkr so it shows the error.
