### ISSUE TITLE
clear_search.jstree event not defined

### ISSUE THREAD

**Issue by hareaca** [deitch/jstree-grid#95]
when you use `$('.jstree').jstree(true).search('')` jstree use `clear_search` and it was not defined. I tried to define this event, but not sure if this is the best way, but u can give a try.

````JavaScript
// add this after search.jstree event
.on("clear_search.jstree", $.proxy(function (e, data) {
// search sometimes filters, so we need to hide all of the appropriate grid cells as well, and show only the matches
  var dataRow = this.dataRow;
    if(this._data.search.som && data.nodes.length) {
      // hide all of the grid cells
      dataRow.find('div.jstree-grid-cell').hide();
      // show only those that match
      this.element.find(".jstree-node").each(function (i,node) {
        var id = node.id;
	if (id) {
          dataRow.find("."+GRIDCELLID_PREFIX+id+GRIDCELLID_POSTFIX).show();
	}
      });
    }
  return true;
}, this));
````

**Comment by deitch** [comment]
I fixed your formatting so this is readable.

**Comment by deitch** [comment]
I don't understand the problem. Doesn't this get called via 'search.jstree'?

**Comment by hareaca** [comment]
http://jsfiddle.net/exc18sgj/ here you can see that clear_search event is fired when use search('')

**Comment by deitch** [comment]
OK, I finally get it. It doesn't call clear_search. Why does it matter? It seems to work.

**Comment by side-by-side** [comment]
I have the same issue. When search is cleared, previously hidden grid rows not showed without defined “clear_search.jstree” event.
deitch, you should test it again and define that missed event.
I use jstree-grid v. 3.2.3 (2015-06-016) and jstree v. 3.2.1

**Comment by deitch** [comment]
This is strange. In my test cases, even without `clear_search.jstree` event handler, it still does the right thing.

Either way, it doesn't hurt. On `clear_search`, just show everything, so I added a simple handler. v3.2.5

I am going to close this issue out now. If this problem still exists, please reopen it with a link to a fiddle showing it failing.

**Comment by side-by-side** [comment]
Thank you very much, everything is fine now.
