### ISSUE TITLE
valueClass not working with JSON object

### ISSUE THREAD

**Issue by jaimeamedina** [deitch/jstree-grid#96]
I'm having an issue working with the valueClass property. If I add a property to the data object to store the value of the class string (i.e., node.data.className), it doesn't appear in the class attribute of the span that contains the value of the column.

After looking at the code where valClass is defined (line 648 in jstreegrid.js), I think that t.attr(col.valueClass) would always be undefined as that property is stored in the objData object rather than t. Is that correct? Forgive me if I've missed something or am adding the property in the wrong place. 

If I replace the valClass declarative with something closer to the way val is defined a bit more previously in the code (see code below), it seems to work. Also, you could have the opportunity to pass a function as a value the as per the value property.

Thanks in advance for your help
Jaime

````JavaScript
if (col.valueClass !== undefined && col.valueClass !== null) {
   if (objData.data !== null && objData.data !== undefined && objData.data[col.valueClass] !== undefined) {
      valClass = objData.data[col.valueClass];
    } else {
      valClass = "";
    }
}
````

**Comment by deitch** [comment]
Why, yes, I think you are right. It should affect a few things in those lines LL647-660.

I want to run some tests....

**Comment by jaimeamedina** [comment]
Hi Avi,

Thanks for getting back to quickly. Let me know the outcome of your
testing.

Thanks again!
Jaime

**Comment by deitch** [comment]
Very nice catch. I am pushing it out now. Thank you.
