### ISSUE TITLE
Syntax error, unrecognized expression: unsupported pseudo: 0_col1

### ISSUE THREAD

**Issue by LeZohan** [deitch/jstree-grid#97]
Hi !

I'm actually trying to use your jstree-grid-master plugin.

It is displaying columns, the collapse works fine but I can't expand any row. On click i get the error message that's in the title of this issue.

Here's my initialization : 

        $('#jstree_demo_div').jstree({

            plugins: ["core", "grid"],

            grid: {
                columns: [
                    {
                        header: "1", width: 200
                    },
                    {
                        header: "2", width: 200
                    },
                    {
                        header: "3", width: 200
                    }
                ]
            },

            'core': {
                'data': myJson
                ]
            }
        });

The "myJson" value is fine, cause it works without the plugin.

I guess I missed something in the doc, but what ?

Thanks !

JQuery version : 1.11.3
JsTree version : The latest (3.3.1 i think)

**Comment by deitch** [comment]
My initial reaction is that you don't appear to have put any data. It uses the `value` property of the column to determine what to show, whether the property or a function. See https://github.com/deitch/jstree-grid/blob/master/README.md#the-options-are-as-follows

But it is hard to be sure without a functioning (or in this case, malfunctioning) example. Can you put up a plunkr or jsfiddle with the error happening? Should be pretty easy with the simple case here.

**Comment by LeZohan** [comment]
Here it is ! 

http://jsfiddle.net/g5r7d6y2/

Btw, on the fiddle, the row is even disappearing Oo

Thanks for your quick answer :)

**Comment by deitch** [comment]
Cool. The error is coming out of jquery. Now, what is triggering it....

**Comment by deitch** [comment]
Hmm, jquery (actually Sizzle) is complaining because there is a ':' in the identifier, which is not legitimate for a node ID (or so it believes; I haven't checked the RFC in a while).

**Comment by deitch** [comment]
Of course it doesn't! Sizzle uses CSS, which treats ':' as a separator between the selector (e.g. `div#abc` or `span.foo`) and CSS pseudos. Hence the error. The code uses `"id":"1286560M:0"` which causes it to be the ID, hence the rest of the trouble.

**Comment by LeZohan** [comment]
Works perfectly !
Thank you very much man ! You just save me ;D
