### ISSUE TITLE
'data' values not displayed correctly

### ISSUE THREAD

**Issue by LeZohan** [deitch/jstree-grid#99]
Hi again !

First of all, sorry for the title, I didn't know how to describe my issue, but, as usual, some code speaks more than a huge text : http://jsfiddle.net/g5r7d6y2/2/

You'll see the unminified json at the bottom of the javascript page.

I tried to use my data values inside a function or just with the attribute name, but there must be some little thing missing, cause i'm not getting my data values for each node, when I collapse, they are stayin (which means the data values are dupplicated if i re-expand them), and they're displayed upside down :/.

I found nothing either in the issues of on StackOverflow :/

**Comment by deitch** [comment]
So is the problem:

1. When you collapse the grid remains;
2. Because of 1, when you expand, you get double entries?

**Comment by LeZohan** [comment]
Yup ! 

+ the grid only appears for my root node and his children, not for all the levels bellow

**Comment by deitch** [comment]
Looks like illegit IDs again. A node ID cannot have whitespace in its name.

**Comment by LeZohan** [comment]
Gonna check this out tomorrow at work ;)

**Comment by LeZohan** [comment]
You were right !

Thanks again ! I do really love your plugin ! :D

**Comment by deitch** [comment]
Very glad you do. Et j'aime voir le français dans votre jsfiddle.

My French is not what it was (grew up in Montréal, but haven't lived there in >20 years), but I still love it.
